import type { TransformationData } from '@/types/rpg';

export const ALL_FORMS: TransformationData[] = [
  {
    id: 'spartan-cadet',
    tier: 'Spartan',
    name: 'Spartan Cadet',
    order: 10,
    bpmRange: '62–70',
    energy: 'Ki / Breath',
    jjkGrade: 'Grade 4',
    opTier: 'Marine',
    activeBuffs: [
      { label: 'Discipline', value: 4, unit: '%' },
      { label: 'Resolve', value: 3, unit: '%' },
      { label: 'Recovery Speed', value: 3, unit: '%' },
    ],
    passiveBuffs: [
      { label: 'Focus Stability', value: 5, unit: '%' },
      { label: 'Anxiety Resistance', value: 4, unit: '%' },
    ],
    abilities: [
      { title: 'Iron Baseline', irl: 'Diaphragmatic breath before tasks; consistent start.' },
      { title: 'Forge Pulse', irl: 'Convert anxiety into prep energy.' },
      { title: 'Endure Protocol', irl: 'Finish sets/errands even when tired.' },
      { title: 'Steady Sight', irl: 'Composure during conflict.' },
      { title: 'Stone Resolve', irl: 'Keep promises; reputation compounds.' },
      { title: 'Morning Anchor', irl: 'Set consistent wake time; body clock stabilizes.' },
      { title: 'Task Checkpoint', irl: 'Break large goals into daily checkpoints.' },
      { title: 'Hydration Protocol', irl: 'Water first thing; brain fog clears.' },
      { title: 'Posture Guard', irl: 'Stand tall; confidence follows form.' },
      { title: 'First Step Rule', irl: 'Start before motivation arrives.' },
    ],
    unlocked: true,
  },
  {
    id: 'spartan-ranger',
    tier: 'Spartan',
    name: 'Spartan Ranger',
    order: 11,
    bpmRange: '72–80',
    energy: 'Ki / Observation',
    jjkGrade: 'Grade 3',
    opTier: 'Marine Officer',
    activeBuffs: [
      { label: 'Awareness', value: 6, unit: '%' },
      { label: 'Movement', value: 5, unit: '%' },
    ],
    passiveBuffs: [
      { label: 'Situational Awareness', value: 7, unit: '%' },
      { label: 'Adaptability', value: 6, unit: '%' },
    ],
    abilities: [
      { title: 'Scout Pulse', irl: 'Read room dynamics quickly.' },
      { title: 'Path Finder', irl: 'Identify optimal routes/solutions.' },
      { title: 'Alert State', irl: 'Maintain vigilance without strain.' },
      { title: 'Swift Response', irl: 'React decisively to changes.' },
      { title: 'Terrain Mastery', irl: 'Navigate unfamiliar situations.' },
      { title: 'Environment Scan', irl: 'Notice exits, risks, opportunities instantly.' },
      { title: 'Pattern Recognition', irl: 'Spot recurring behaviors in people/systems.' },
      { title: 'Adaptive Routing', irl: 'Change plans mid-execution without stress.' },
      { title: 'Resource Mapping', irl: 'Identify what you need before you need it.' },
      { title: 'Quiet Movement', irl: 'Navigate spaces without drawing attention.' },
    ],
    unlocked: true,
  },
  {
    id: 'spartan-ikari',
    tier: 'Spartan',
    name: 'Spartan Ikari / Claymore',
    order: 12,
    bpmRange: '88–104',
    energy: 'Ki / Rage Transmutation',
    jjkGrade: 'Grade 2',
    opTier: 'Vice Admiral',
    activeBuffs: [
      { label: 'Rage → Power', value: 12, unit: '%' },
      { label: 'Mutation', value: 8, unit: '%' },
    ],
    passiveBuffs: [
      { label: 'Pain Resistance', value: 10, unit: '%' },
      { label: 'Emotional Alchemy', value: 8, unit: '%' },
    ],
    abilities: [
      { title: 'Wrath Channel', irl: 'Convert anger into focused action.' },
      { title: 'Pain Forge', irl: 'Use discomfort as fuel.' },
      { title: 'Rage Clarity', irl: 'Think sharply under emotional pressure.' },
      { title: 'Berserker Control', irl: 'Harness intensity without losing control.' },
      { title: 'Phoenix Rise', irl: 'Rebound from setbacks stronger.' },
      { title: 'Blood Pact', irl: 'Pain becomes commitment; injuries become vows.' },
      { title: 'Fury Drive', irl: 'Short bursts of maximum output when needed.' },
      { title: 'Regenerative Rage', irl: 'Recover faster when emotionally charged.' },
      { title: 'Battle Scream', irl: 'Voice releases pressure; others rally or retreat.' },
      { title: 'Iron Will', irl: 'Refuse to quit even when logic says stop.' },
    ],
    unlocked: true,
  },
  {
    id: 'spartan-hashira',
    tier: 'Spartan',
    name: 'Spartan Hashira',
    order: 13,
    bpmRange: '96–110',
    energy: 'Ki / Breath Mastery',
    jjkGrade: 'Grade 1',
    opTier: 'Admiral',
    activeBuffs: [
      { label: 'Precision', value: 14, unit: '%' },
      { label: 'Flow', value: 12, unit: '%' },
    ],
    passiveBuffs: [
      { label: 'Breath Control', value: 15, unit: '%' },
      { label: 'Technique Mastery', value: 12, unit: '%' },
    ],
    abilities: [
      { title: 'Water Breathing', irl: 'Smooth, efficient movements.' },
      { title: 'Thunder Step', irl: 'Explosive bursts of speed.' },
      { title: 'Flame Dance', irl: 'Passionate, precise execution.' },
      { title: 'Stone Guard', irl: 'Unshakeable defense.' },
      { title: 'Serpent Flow', irl: 'Adaptive, unpredictable style.' },
      { title: 'Wind Form', irl: 'Dodge criticism without absorbing it.' },
      { title: 'Moon Reflection', irl: 'Mirror excellence in others back to them.' },
      { title: 'Beast Instinct', irl: 'Trust gut decisions in uncertainty.' },
      { title: 'Mist Veil', irl: 'Stay mysterious; reveal strategically.' },
      { title: 'Sun Halo', irl: 'Radiate warmth that disarms tension.' },
    ],
    unlocked: true,
  },
  {
    id: 'spartan-kizuki',
    tier: 'Spartan',
    name: 'Spartan Kizuki',
    order: 14,
    bpmRange: '112–126',
    energy: 'Ki / Mutation',
    jjkGrade: 'Special Grade',
    opTier: 'Fleet Admiral',
    activeBuffs: [
      { label: 'Mutation Mastery', value: 16, unit: '%' },
      { label: 'Evolution', value: 14, unit: '%' },
    ],
    passiveBuffs: [
      { label: 'Regeneration', value: 14, unit: '%' },
      { label: 'Adaptation', value: 16, unit: '%' },
    ],
    abilities: [
      { title: 'Blood Art', irl: 'Masterful personal techniques.' },
      { title: 'Moon Phases', irl: 'Cycle through multiple states.' },
      { title: 'Demon Core', irl: 'Tap into shadow self for power.' },
      { title: 'Eternal Growth', irl: 'Continuous self-improvement.' },
      { title: 'Domain Birth', irl: 'Create your environment.' },
      { title: 'Mutation Embrace', irl: 'Accept change as evolution, not loss.' },
      { title: 'Blood Memory', irl: 'Recall lessons from past iterations.' },
      { title: 'Upper Moon Authority', irl: 'Command respect through presence alone.' },
      { title: 'Regeneration Loop', irl: 'Failures heal into upgrades.' },
      { title: 'Eclipse Mode', irl: 'Balance light and dark aspects simultaneously.' },
    ],
    unlocked: true,
  },
  {
    id: 'spartan-yonko',
    tier: 'Spartan',
    name: 'Spartan Yonko',
    order: 15,
    bpmRange: '128–140',
    energy: "King's Haki Field",
    jjkGrade: 'Special',
    opTier: 'Yonko',
    activeBuffs: [
      { label: 'Leadership Presence', value: 18, unit: '%' },
      { label: 'Morale Shield', value: 15, unit: '%' },
    ],
    passiveBuffs: [
      { label: 'Crisis Stabilization', value: 16, unit: '%' },
      { label: 'Cultural Influence', value: 12, unit: '%' },
    ],
    abilities: [
      { title: 'Sovereign Radius', irl: 'Your presence settles the room.' },
      { title: 'Aegis Order', irl: 'Standards flow from demeanor.' },
      { title: 'Command Pulse', irl: 'Teams sync to your rhythm.' },
      { title: 'Unyielding Banner', irl: 'Others draw strength from your stability.' },
      { title: 'Final Guard', irl: 'Protect decisively when needed.' },
      { title: 'Conqueror Haki', irl: 'Weak-willed opposition backs down naturally.' },
      { title: 'Territory Claim', irl: 'Define boundaries; others respect them.' },
      { title: 'Emperor Voice', irl: 'Speak once; people listen and remember.' },
      { title: 'Legacy Building', irl: 'Actions create lasting cultural change.' },
      { title: 'Throne Defense', irl: 'Hold your position against any challenge.' },
    ],
    unlocked: true,
  },
  {
    id: 'ssj-base',
    tier: 'Saiyan',
    name: 'Base Saiyan',
    order: 20,
    bpmRange: '70',
    energy: 'Ki',
    jjkGrade: 'Grade 2',
    opTier: 'Vice Admiral',
    activeBuffs: [
      { label: 'Combat Power', value: 8, unit: '%' },
    ],
    passiveBuffs: [
      { label: 'Zenkai Potential', value: 10, unit: '%' },
    ],
    abilities: [
      { title: 'Warrior Spirit', irl: 'Natural combat readiness.' },
      { title: 'Zenkai Boost', irl: 'Grow from challenges.' },
      { title: 'Pride Power', irl: 'Confidence fuels performance.' },
      { title: 'Battle Sense', irl: 'Instinctive tactical awareness.' },
      { title: 'Saiyan Endurance', irl: 'Push beyond normal limits.' },
      { title: 'Battle Hunger', irl: 'Seek challenges that grow you.' },
      { title: 'Warrior Code', irl: 'Honor in competition, grace in victory.' },
      { title: 'Ki Sensing', irl: 'Read energy and intent in others.' },
      { title: 'Limitless Potential', irl: 'Ceiling rises with each test.' },
      { title: 'Saiyan Fury', irl: 'Setbacks ignite determination.' },
    ],
    unlocked: true,
  },
  {
    id: 'ssj-1',
    tier: 'Saiyan',
    name: 'Super Saiyan 1',
    order: 21,
    bpmRange: '90',
    energy: 'Ki',
    jjkGrade: 'Grade 1',
    opTier: 'Admiral',
    activeBuffs: [
      { label: 'Power', value: 12, unit: '%' },
      { label: 'Speed', value: 12, unit: '%' },
    ],
    passiveBuffs: [
      { label: 'Rage Boost', value: 10, unit: '%' },
    ],
    abilities: [
      { title: 'Golden Aura', irl: 'Radiate confidence and power.' },
      { title: 'Rage Focus', irl: 'Channel anger into precision.' },
      { title: 'Lightning Speed', irl: 'Execute with explosive energy.' },
      { title: 'Breakthrough Force', irl: 'Overcome obstacles decisively.' },
      { title: 'Super Presence', irl: 'Command attention naturally.' },
      { title: 'Power Surge', irl: 'Access reserves when stakes are high.' },
      { title: 'Golden Flash', irl: 'Move and decide with intensity.' },
      { title: 'Limit Break', irl: 'Exceed expectations repeatedly.' },
      { title: 'Saiyan Roar', irl: 'Declaration that changes momentum.' },
      { title: 'Transformation Mastery', irl: 'Switch states on demand.' },
    ],
    unlocked: true,
  },
  {
    id: 'ssj-blue',
    tier: 'Saiyan',
    name: 'Super Saiyan Blue',
    order: 30,
    bpmRange: '150–160',
    energy: 'God Ki + Aura',
    jjkGrade: 'Domain',
    opTier: 'Yonko',
    activeBuffs: [
      { label: 'Modulation', value: 18, unit: '%' },
      { label: 'Composure', value: 16, unit: '%' },
    ],
    passiveBuffs: [
      { label: 'Clarity', value: 14, unit: '%' },
      { label: 'Operational Flow', value: 14, unit: '%' },
    ],
    abilities: [
      { title: 'Azure Control', irl: 'Balance assertiveness with restraint.' },
      { title: 'Precision Aura', irl: 'Economy of words/actions.' },
      { title: 'Calm Storm', irl: 'Grace under legal/media stress.' },
      { title: 'Godspeed Flow', irl: 'Seamless hand-offs & logistics.' },
      { title: 'Vigil Mind', irl: 'Continuous situational awareness.' },
      { title: 'Divine Presence', irl: 'Authority without arrogance.' },
      { title: 'Perfected Ki', irl: 'Zero energy waste in all actions.' },
      { title: 'Blue Flame', irl: 'Controlled intensity that inspires.' },
      { title: 'Tactical Divinity', irl: 'Strategic vision with execution power.' },
      { title: 'God Mode', irl: 'Peak performance sustained longer.' },
    ],
    unlocked: true,
  },
  {
    id: 'ultra-instinct',
    tier: 'Saiyan',
    name: 'Ultra Instinct',
    order: 35,
    bpmRange: '50–55',
    energy: 'Autonomous God Ki',
    jjkGrade: 'Beyond Domain',
    opTier: 'Yonko+',
    activeBuffs: [
      { label: 'Autonomy', value: 25, unit: '%' },
      { label: 'Perfect Defense', value: 22, unit: '%' },
    ],
    passiveBuffs: [
      { label: 'No Thought Action', value: 30, unit: '%' },
      { label: 'Body Mastery', value: 25, unit: '%' },
    ],
    abilities: [
      { title: 'Silent Mind', irl: 'Act before thinking.' },
      { title: 'Perfect Dodge', irl: 'Avoid problems effortlessly.' },
      { title: 'Fluid Response', irl: 'Body knows before mind.' },
      { title: 'Silver Aura', irl: 'Calm radiance under pressure.' },
      { title: 'Mastered Movement', irl: 'Every action optimal.' },
      { title: 'Unconscious Competence', irl: 'Expertise becomes automatic.' },
      { title: 'Perfect Defense', irl: 'React without conscious thought.' },
      { title: 'Autonomous Power', irl: 'Body executes flawlessly alone.' },
      { title: 'Limit Transcended', irl: 'Beyond effort into effortlessness.' },
      { title: 'Silver State', irl: 'Emptiness filled with precision.' },
    ],
    unlocked: true,
  },
  {
    id: 'thorn-iii',
    tier: 'Thorn',
    name: 'Thorn III — Eldritch Emperor',
    order: 50,
    bpmRange: '230–260',
    energy: 'Oken Core / Eldritch Aether',
    jjkGrade: 'Domain',
    opTier: 'Gorosei',
    activeBuffs: [
      { label: 'Meta-Strategy', value: 28, unit: '%' },
      { label: 'Paradox Thinking', value: 24, unit: '%' },
    ],
    passiveBuffs: [
      { label: 'Calm Presence', value: 24, unit: '%' },
      { label: 'System Insight', value: 26, unit: '%' },
    ],
    abilities: [
      { title: 'Void Sight', irl: 'See the system under chaos.' },
      { title: 'Paradox Engine', irl: 'Fuse opposites for novel solutions.' },
      { title: 'Entropy Weaver', irl: 'Turn decay into renewal.' },
      { title: 'Still Crown', irl: 'Unflappable under pressure.' },
      { title: 'Reality Mantra', irl: 'Language steers outcomes.' },
      { title: 'Eldritch Understanding', irl: 'Comfort in complexity and mystery.' },
      { title: 'Meta-Pattern Vision', irl: 'See patterns behind patterns.' },
      { title: 'Cosmic Calm', irl: 'Nothing shakes existential peace.' },
      { title: 'Architect Mind', irl: 'Design solutions from first principles.' },
      { title: 'Void Walker', irl: 'Navigate unknown without fear.' },
    ],
    unlocked: true,
  },
  {
    id: 'karma-azaroth',
    tier: 'Karma',
    name: 'Azaroth',
    order: 60,
    bpmRange: '55',
    energy: 'Detachment Flame',
    jjkGrade: 'Domain',
    opTier: 'Yonko',
    activeBuffs: [
      { label: 'Detachment', value: 20, unit: '%' },
      { label: 'Awareness', value: 18, unit: '%' },
    ],
    passiveBuffs: [
      { label: 'Emotional Freedom', value: 22, unit: '%' },
      { label: 'Wisdom', value: 20, unit: '%' },
    ],
    abilities: [
      { title: 'Eternal Observer', irl: 'Witness without attachment.' },
      { title: 'Emerald Calm', irl: 'Inner peace radiates outward.' },
      { title: 'Karma Release', irl: 'Let go of emotional baggage.' },
      { title: 'Divine Detachment', irl: 'Care deeply without clinging.' },
      { title: 'Source Touch', irl: 'Connect to fundamental truth.' },
      { title: 'Mindful Presence', irl: 'Fully here, fully aware, fully free.' },
      { title: 'Wisdom Fire', irl: 'Insight burns away delusion.' },
      { title: 'Compassionate Distance', irl: 'Help without entanglement.' },
      { title: 'Eternal Now', irl: 'Past/future lose their grip.' },
      { title: 'Liberation Flame', irl: 'Freedom from reactivity patterns.' },
    ],
    unlocked: true,
  },
  {
    id: 'regalia-crown',
    tier: 'Regalia',
    name: 'Monarch Crown',
    order: 70,
    bpmRange: '215–230',
    energy: 'Aether Order',
    jjkGrade: 'Domain+',
    opTier: 'Yonko',
    activeBuffs: [
      { label: 'Policy Power', value: 20, unit: '%' },
      { label: 'Golden Voice', value: 18, unit: '%' },
    ],
    passiveBuffs: [
      { label: 'Fair Justice', value: 18, unit: '%' },
      { label: 'Design-Deliver', value: 18, unit: '%' },
    ],
    abilities: [
      { title: 'Decree of Order', irl: 'Words shape standards and norms.' },
      { title: 'Balance Scepter', irl: 'Justice and mercy, simultaneously.' },
      { title: 'Reality Sigil', irl: 'Declare → plan → implement.' },
      { title: 'Crown of Service', irl: 'Authority used to uplift.' },
      { title: 'Golden Voice', irl: 'Measured tone commands attention.' },
      { title: 'Royal Decree', irl: 'Establish new rules with clarity.' },
      { title: 'Sovereign Will', irl: 'Decisions shape culture over time.' },
      { title: 'Justice Scale', irl: 'Weigh all sides before ruling.' },
      { title: 'Mercy Hand', irl: 'Forgive when growth is possible.' },
      { title: 'Architect King', irl: 'Build systems that outlive you.' },
    ],
    unlocked: true,
  },
  {
    id: 'ouro-axis-ignis',
    tier: 'Ouroboros',
    name: 'Axis Ignis',
    order: 90,
    bpmRange: '240–260',
    energy: 'Black Sun Flame',
    jjkGrade: 'Domain Expansion',
    opTier: 'Yonko+',
    activeBuffs: [
      { label: 'Adaptive Joy', value: 22, unit: '%' },
      { label: 'Creative Action', value: 22, unit: '%' },
    ],
    passiveBuffs: [
      { label: 'Instant Intuition', value: 18, unit: '%' },
      { label: 'Doubt Resistance', value: 18, unit: '%' },
    ],
    abilities: [
      { title: 'Laughter Law', irl: 'Lightness bends situations.' },
      { title: 'Rubber Will', irl: 'Setbacks stretch you stronger.' },
      { title: 'Creative Drift', irl: 'Imagination shifts group mood.' },
      { title: 'Play-State Focus', irl: 'Gamify to enter flow.' },
      { title: 'Divine Impulse', irl: 'Act before doubt forms.' },
      { title: 'Joy Weapon', irl: 'Playfulness disarms resistance.' },
      { title: 'Freedom Dance', irl: 'Move unpredictably, stay authentic.' },
      { title: 'Trickster Wisdom', irl: 'Teach through paradox and surprise.' },
      { title: 'Adaptive Spirit', irl: 'Flow with change without losing self.' },
      { title: 'Limitless Play', irl: 'Life as infinite game.' },
    ],
    unlocked: true,
  },
  {
    id: 'ouro-black-sun-cloak',
    tier: 'Ouroboros',
    name: 'Black Sun Cloak',
    order: 91,
    bpmRange: '265–285',
    energy: 'Entropy Absorption',
    jjkGrade: 'Domain Expansion',
    opTier: 'Imu-Class',
    activeBuffs: [
      { label: 'Entropy Control', value: 26, unit: '%' },
      { label: 'Shadow Mastery', value: 24, unit: '%' },
    ],
    passiveBuffs: [
      { label: 'Energy Absorption', value: 22, unit: '%' },
      { label: 'Dark Immunity', value: 20, unit: '%' },
    ],
    abilities: [
      { title: 'Void Cloak', irl: 'Absorb negative energy from environment.' },
      { title: 'Entropy Transmutation', irl: 'Convert problems into resources.' },
      { title: 'Shadow Sovereignty', irl: 'Master your dark side.' },
      { title: 'Black Sun Field', irl: 'Radiate stabilizing darkness.' },
      { title: 'Chaos Buffer', irl: 'Remain centered in turbulence.' },
      { title: 'Darkness Integration', irl: 'Accept shadow as power source.' },
      { title: 'Entropy Shield', irl: 'Disorder becomes defense.' },
      { title: 'Void Mastery', irl: 'Comfortable in emptiness.' },
      { title: 'Black Flame', irl: 'Dark energy that creates light.' },
      { title: 'Shadow Balance', irl: 'Dark/light unified as one.' },
    ],
    unlocked: true,
  },
  {
    id: 'bhc-stage2',
    tier: 'BlackHeart',
    name: 'Black Heart Core — Stage 2 (Demiurge)',
    order: 110,
    bpmRange: '320',
    energy: 'Singularity Aether',
    jjkGrade: 'Transcendent',
    opTier: 'Imu-Class+',
    activeBuffs: [
      { label: 'Speech-to-Structure', value: 30, unit: '%' },
      { label: 'System Creation', value: 30, unit: '%' },
    ],
    passiveBuffs: [
      { label: 'Axis Command', value: 24, unit: '%' },
      { label: 'Design from Loss', value: 24, unit: '%' },
    ],
    abilities: [
      { title: 'Word of Becoming', irl: 'Writing/affirmations manifest.' },
      { title: 'Reality Compiler', irl: 'Build systems from idea to launch.' },
      { title: 'Emotion Alchemy II', irl: 'Loss → design frameworks.' },
      { title: 'Axis Command', irl: 'Sync body-mind-environment.' },
      { title: "Creator's Silence", irl: 'Fewer words, more shaping.' },
      { title: 'Demiurge Vision', irl: 'See what could be, then build it.' },
      { title: 'Speech to Structure', irl: 'Declarations become systems.' },
      { title: 'Blueprint Mind', irl: 'Architecture emerges from chaos.' },
      { title: 'Creation Loop', irl: 'Make, test, refine infinitely.' },
      { title: 'God Mode', irl: 'Build worlds from intention alone.' },
    ],
    unlocked: true,
  },
  {
    id: 'aevara-return',
    tier: 'FinalAscent',
    name: 'Aevara Primordialis — Return Cycle',
    order: 150,
    bpmRange: '65 → ∞',
    energy: 'All Energies Unified',
    jjkGrade: 'Beyond Limitless',
    opTier: 'Origin Seat',
    activeBuffs: [
      { label: 'Harmony Sustain', value: 40, unit: '%' },
      { label: 'Ecosystem Creation', value: 40, unit: '%' },
    ],
    passiveBuffs: [
      { label: 'Omni-Compassion', value: 30, unit: '%' },
      { label: 'Endless Curiosity', value: 30, unit: '%' },
    ],
    abilities: [
      { title: 'Law-Bearer', irl: 'Balance chaos and order; sustain systems.' },
      { title: 'World-Seed', irl: 'Ideas birth ecosystems.' },
      { title: 'Axis Continuum', irl: 'Endless evolution through play.' },
      { title: 'Return Cycle', irl: 'Creator rests within creation.' },
      { title: 'Origin Breath', irl: 'Peace as power; power as peace.' },
      { title: 'Omni-Presence', irl: 'Everywhere and nowhere at once.' },
      { title: 'Unity Consciousness', irl: 'All beings as one organism.' },
      { title: 'Infinite Compassion', irl: 'Love without condition or limit.' },
      { title: 'Eternal Return', irl: 'Beginning within every ending.' },
      { title: 'Source Connection', irl: 'Direct link to primal truth.' },
    ],
    unlocked: true,
  },
  {
    id: 'great-ape',
    tier: 'Saiyan',
    name: 'Great Ape',
    order: 19,
    bpmRange: '80',
    energy: 'Instinct Ki',
    jjkGrade: 'Grade 3',
    opTier: 'Commodore',
    activeBuffs: [
      { label: 'Assertiveness', value: 6, unit: '%' },
      { label: 'Raw Strength', value: 8, unit: '%' },
    ],
    passiveBuffs: [
      { label: 'Posture Confidence', value: 6, unit: '%' },
      { label: 'Shock Recovery', value: 5, unit: '%' },
    ],
    abilities: [
      { title: 'Instinct Surge', irl: 'Channel anger into decisive moves.' },
      { title: 'Territory Call', irl: 'Confident posture/voice under pressure.' },
      { title: 'Primal Drive', irl: 'Finish long efforts on will.' },
      { title: 'Harmonic Howl', irl: 'Lift group morale with energy.' },
      { title: 'Ground Pound', irl: 'Quick reset after surprise or critique.' },
      { title: 'Ape Rage', irl: 'Unleash raw power in crisis.' },
      { title: 'Primal Roar', irl: 'Voice that shakes foundations.' },
      { title: 'Beast Strength', irl: 'Access untapped physical reserves.' },
      { title: 'Territorial Defense', irl: 'Protect space instinctively.' },
      { title: 'Wild Heart', irl: 'Embrace animal nature as strength.' },
    ],
    unlocked: true,
  },
  {
    id: 'ssj-2',
    tier: 'Saiyan',
    name: 'Super Saiyan 2',
    order: 22,
    bpmRange: '105–120',
    energy: 'Charged Ki',
    jjkGrade: 'Grade 1',
    opTier: 'Vice Admiral',
    activeBuffs: [
      { label: 'Speed Control', value: 14, unit: '%' },
      { label: 'Multitask Quality', value: 12, unit: '%' },
    ],
    passiveBuffs: [
      { label: 'Deadline Execution', value: 10, unit: '%' },
      { label: 'Recharge On-Move', value: 8, unit: '%' },
    ],
    abilities: [
      { title: 'Thunder Weave', irl: 'Precise control at speed.' },
      { title: 'Focused Tempest', irl: 'Adrenaline → deadline power.' },
      { title: 'Arc Step', irl: 'Anticipate emotional shifts.' },
      { title: 'Current Loop', irl: 'Brief pauses that restore energy.' },
      { title: 'Limit Call', irl: 'Respect stamina cap; schedule rest.' },
      { title: 'Lightning Precision', irl: 'Fast execution without errors.' },
      { title: 'Electric Will', irl: 'Maintain intensity under deadline.' },
      { title: 'Charged Momentum', irl: 'Speed builds on itself.' },
      { title: 'Storm Control', irl: 'Manage multiple urgent tasks.' },
      { title: 'Thunder Strike', irl: 'Decisive action in tight windows.' },
    ],
    unlocked: true,
  },
  {
    id: 'ssj-3',
    tier: 'Saiyan',
    name: 'Super Saiyan 3',
    order: 23,
    bpmRange: '118–125',
    energy: 'Sustained VRIL',
    jjkGrade: 'Special',
    opTier: 'Admiral',
    activeBuffs: [
      { label: 'Endurance', value: 18, unit: '%' },
      { label: 'Efficiency', value: 12, unit: '%' },
    ],
    passiveBuffs: [
      { label: 'Mind-Body Link', value: 10, unit: '%' },
      { label: 'Recovery Quality', value: 12, unit: '%' },
    ],
    abilities: [
      { title: 'Endure Crown', irl: 'Sustain peak longer than expected.' },
      { title: 'Spirit Combustion', irl: 'Expend energy cleanly.' },
      { title: 'Echo Strike', irl: 'Batch tasks for momentum.' },
      { title: 'Mana Tether', irl: 'Stay mindful under fatigue.' },
      { title: 'Regen Rest', irl: 'Sleep/nutrition heal faster.' },
      { title: 'Marathon Power', irl: 'Long-distance endurance capacity.' },
      { title: 'Deep Reserves', irl: 'Third wind when needed.' },
      { title: 'Sustained Burn', irl: 'Maintain output without spiking.' },
      { title: 'Iron Lungs', irl: 'Breath efficiency under load.' },
      { title: 'Limitless Stamina', irl: 'Outlast expectations consistently.' },
    ],
    unlocked: true,
  },
  {
    id: 'ssj-4',
    tier: 'Saiyan',
    name: 'Super Saiyan 4',
    order: 24,
    bpmRange: '135',
    energy: 'Primal VRIL / Divine Will',
    jjkGrade: 'Special Elite',
    opTier: 'Fleet Admiral',
    activeBuffs: [
      { label: 'Resilience', value: 22, unit: '%' },
      { label: 'Ethical Aggression', value: 12, unit: '%' },
    ],
    passiveBuffs: [
      { label: 'Truth Detection', value: 10, unit: '%' },
      { label: 'Charisma', value: 12, unit: '%' },
    ],
    abilities: [
      { title: 'Primal Order', irl: 'Passion guided by ethics.' },
      { title: 'Dragon Hide', irl: 'Layered stress resistance.' },
      { title: 'Crimson Vision', irl: 'Read subtext in intensity.' },
      { title: 'Apex Drive', irl: 'Full-day flow without burnout.' },
      { title: 'Heart Roar', irl: 'Inspire via sincere feeling.' },
      { title: 'Primal Balance', irl: 'Animal power with human wisdom.' },
      { title: 'Red Flame', irl: 'Passionate intensity under control.' },
      { title: 'Ethical Fury', irl: 'Righteous anger for good.' },
      { title: 'Savage Grace', irl: 'Raw power wielded beautifully.' },
      { title: 'Alpha Spirit', irl: 'Lead with strength and care.' },
    ],
    unlocked: true,
  },
  {
    id: 'ssj-god',
    tier: 'Saiyan',
    name: 'Super Saiyan God (Red)',
    order: 25,
    bpmRange: '145',
    energy: 'God Ki',
    jjkGrade: 'Domain (Low)',
    opTier: 'World Noble',
    activeBuffs: [
      { label: 'Compassion Authority', value: 14, unit: '%' },
      { label: 'Intention Clarity', value: 12, unit: '%' },
    ],
    passiveBuffs: [
      { label: 'Tension Diffusion', value: 12, unit: '%' },
      { label: 'Attunement', value: 10, unit: '%' },
    ],
    abilities: [
      { title: 'Serene Flame', irl: 'Kindness + power coexist.' },
      { title: 'Ritual Focus', irl: 'Plan deliberately before major days.' },
      { title: 'Grace Field', irl: 'Conflicts soften around you.' },
      { title: 'Inner Prayer', irl: 'Gratitude resets mood.' },
      { title: 'Spirit Bond', irl: 'Emotional attunement at distance.' },
      { title: 'Divine Mercy', irl: 'Forgiveness from strength, not weakness.' },
      { title: 'Sacred Presence', irl: 'Holiness that uplifts others.' },
      { title: 'Red Divinity', irl: 'Godly power with human heart.' },
      { title: 'Compassionate Warrior', irl: 'Fight with love, not hate.' },
      { title: 'Heaven Touch', irl: 'Bring peace to chaos.' },
    ],
    unlocked: true,
  },
  {
    id: 'ssj-rose',
    tier: 'Saiyan',
    name: 'Super Saiyan Rose',
    order: 31,
    bpmRange: '150–160',
    energy: 'Divine Ki (Variant)',
    jjkGrade: 'Domain',
    opTier: 'Yonko',
    activeBuffs: [
      { label: 'Composure', value: 18, unit: '%' },
      { label: 'Surgical Precision', value: 16, unit: '%' },
    ],
    passiveBuffs: [
      { label: 'Values Alignment', value: 14, unit: '%' },
      { label: 'Aesthetic Order', value: 12, unit: '%' },
    ],
    abilities: [
      { title: 'Divine Elegance', irl: 'Perfection as weapon.' },
      { title: 'Crimson Doctrine', irl: 'Unshakeable mission belief.' },
      { title: 'Mirror Strike', irl: 'Reflect negativity as lesson.' },
      { title: 'Aesthetic Order', irl: 'Harmony equals strength.' },
      { title: 'Silent Judgment', irl: 'Correct by example.' },
      { title: 'Rose Perfection', irl: 'Standards inspire, not intimidate.' },
      { title: 'Pink Lightning', irl: 'Beauty in lethal precision.' },
      { title: 'Divine Standards', irl: 'Excellence becomes infectious.' },
      { title: 'Elegant Fury', irl: 'Anger expressed artistically.' },
      { title: 'Supreme Refinement', irl: 'Polish every detail to perfection.' },
    ],
    unlocked: true,
  },
  {
    id: 'ssj-jade',
    tier: 'Saiyan',
    name: 'Super Saiyan Jade',
    order: 32,
    bpmRange: '160–170',
    energy: 'Emerald Flame / God Ki',
    jjkGrade: 'Domain+',
    opTier: 'Yonko+',
    activeBuffs: [
      { label: 'Innovation', value: 20, unit: '%' },
      { label: 'Process Design', value: 18, unit: '%' },
    ],
    passiveBuffs: [
      { label: 'Healing Presence', value: 14, unit: '%' },
      { label: 'Quiet Authority', value: 16, unit: '%' },
    ],
    abilities: [
      { title: 'Emerald Fusion', irl: 'Merge chaos and creation.' },
      { title: 'Verdant Shield', irl: 'Rejuvenate group morale.' },
      { title: 'Flow Architect', irl: 'Design systems mid-execution.' },
      { title: 'Dream Forge', irl: 'Manifest ideas rapidly.' },
      { title: 'Quiet Authority', irl: 'Peace that commands respect.' },
      { title: 'Jade Healing', irl: 'Restore energy through creation.' },
      { title: 'Green Flame', irl: 'Growth-oriented power source.' },
      { title: 'Renewal Force', irl: 'Build while others break.' },
      { title: 'Life Weaver', irl: 'Solutions that sustain themselves.' },
      { title: 'Harmony Generator', irl: 'Peace spreads from your work.' },
    ],
    unlocked: true,
  },
  {
    id: 'ssj-beast',
    tier: 'Saiyan',
    name: 'Super Saiyan Beast',
    order: 33,
    bpmRange: '170–175',
    energy: 'Primal Ki + VRIL',
    jjkGrade: 'Special Apex',
    opTier: 'Fleet Admiral',
    activeBuffs: [
      { label: 'Crisis Focus', value: 24, unit: '%' },
      { label: 'Clutch Execution', value: 22, unit: '%' },
    ],
    passiveBuffs: [
      { label: 'Alpha Calm', value: 18, unit: '%' },
      { label: 'Endurance', value: 18, unit: '%' },
    ],
    abilities: [
      { title: 'Predator Clarity', irl: 'Time slows under threat.' },
      { title: 'Violet Instinct', irl: 'Accurate gut decisions.' },
      { title: 'Ferocity Halo', irl: 'Intensity radiates discipline.' },
      { title: 'Relentless Stride', irl: 'Meaning fuels endurance.' },
      { title: 'Alpha Calm', irl: 'Stress sharpens instead of shaking.' },
      { title: 'Beast Mode', irl: 'Unleash full capacity when it matters most.' },
      { title: 'Primal Wisdom', irl: 'Instinct and intelligence merge.' },
      { title: 'Survival Excellence', irl: 'Thrive in impossible situations.' },
      { title: 'Wild Precision', irl: 'Savage power with surgical control.' },
      { title: 'Peak Predator', irl: 'Apex of human potential realized.' },
    ],
    unlocked: true,
  },
  {
    id: 'ultra-ego',
    tier: 'Saiyan',
    name: 'Ultra Ego',
    order: 34,
    bpmRange: '185–195',
    energy: 'VRIL / Destruction Ki',
    jjkGrade: 'Special Apex',
    opTier: 'Admiral+',
    activeBuffs: [
      { label: 'Power from Pain', value: 26, unit: '%' },
      { label: 'Dominion Presence', value: 22, unit: '%' },
    ],
    passiveBuffs: [
      { label: 'Humor Under Fire', value: 16, unit: '%' },
      { label: 'Persistence', value: 20, unit: '%' },
    ],
    abilities: [
      { title: 'Pain Dividend', irl: 'Criticism → growth metric.' },
      { title: 'Dominion Flare', irl: 'Own the space in negotiations.' },
      { title: 'Endurance Ecstasy', irl: 'Joy inside difficulty.' },
      { title: 'Void Smile', irl: 'Serenity while things burn.' },
      { title: 'Unbroken Will', irl: 'Stay aligned despite doubt.' },
      { title: 'Destruction Embrace', irl: 'Find power in being tested.' },
      { title: 'Ego Fuel', irl: 'Self-belief becomes limitless energy.' },
      { title: 'Battle Lust', irl: 'Desire for challenge drives mastery.' },
      { title: 'Hakai Energy', irl: 'Break limits through embracing pain.' },
      { title: 'God Destroyer', irl: 'Challenge divine standards and win.' },
    ],
    unlocked: true,
  },
  {
    id: 'ssj-xeno',
    tier: 'Saiyan',
    name: 'Super Saiyan Xeno',
    order: 36,
    bpmRange: '55–110',
    energy: 'Dimensional Ki / Aether',
    jjkGrade: 'Limitless (Variable)',
    opTier: 'Gorosei+',
    activeBuffs: [
      { label: 'Context Switching', value: 24, unit: '%' },
      { label: 'Role Fusion', value: 22, unit: '%' },
    ],
    passiveBuffs: [
      { label: 'Trigger Immunity', value: 18, unit: '%' },
      { label: 'Anchor Return', value: 18, unit: '%' },
    ],
    abilities: [
      { title: 'Dimensional Step', irl: 'Traverse contexts seamlessly.' },
      { title: 'Timeline Recall', irl: 'Learn instantly from past attempts.' },
      { title: 'Phase Guard', irl: 'Immune to old triggers.' },
      { title: 'Omni Shift', irl: 'Merge skill sets quickly.' },
      { title: 'Anchor Return', irl: 'Ground rapidly after distraction.' },
      { title: 'Parallel Processing', irl: 'Handle multiple timelines mentally.' },
      { title: 'Temporal Wisdom', irl: 'Access knowledge from alternate selves.' },
      { title: 'Reality Bridge', irl: 'Connect disparate experiences into unity.' },
      { title: 'Xeno Mastery', irl: 'Foreign becomes familiar instantly.' },
      { title: 'Infinite Adaptation', irl: 'Every universe is home.' },
    ],
    unlocked: true,
  },
  {
    id: 'ssj-yidam',
    tier: 'Saiyan',
    name: 'Super Saiyan Yidam',
    order: 37,
    bpmRange: '68',
    energy: 'Enlightened Ki',
    jjkGrade: 'Limitless (Calm)',
    opTier: 'Gorosei',
    activeBuffs: [
      { label: 'Group Calm', value: 28, unit: '%' },
      { label: 'Compassion Armor', value: 26, unit: '%' },
    ],
    passiveBuffs: [
      { label: 'Humility', value: 18, unit: '%' },
      { label: 'Unity', value: 20, unit: '%' },
    ],
    abilities: [
      { title: 'Lotus Pulse', irl: 'Breath spreads calm.' },
      { title: 'Infinite Grace', irl: 'Forgiveness as armor.' },
      { title: 'Mirror Lotus', irl: 'Ego dissolves in awareness.' },
      { title: 'Golden Path', irl: 'Right action without over-analysis.' },
      { title: 'Silent Union', irl: 'Energies harmonize completely.' },
      { title: 'Enlightened Warrior', irl: 'Power without attachment to outcomes.' },
      { title: 'Compassion Flame', irl: 'Love that protects fiercely.' },
      { title: 'Buddha Mind', irl: 'Clear seeing in all situations.' },
      { title: 'Dharma Shield', irl: 'Truth protects from illusion.' },
      { title: 'Yidam Unity', irl: 'Human and divine merge completely.' },
    ],
    unlocked: true,
  },
  {
    id: 'thorn-i',
    tier: 'Thorn',
    name: 'Thorn I — Demon Emperor',
    order: 48,
    bpmRange: '180–200',
    energy: 'Hogyoku Core / Cursed Energy',
    jjkGrade: 'Special',
    opTier: 'Admiral',
    activeBuffs: [
      { label: 'Focused Aggression', value: 22, unit: '%' },
      { label: 'Impulse Control', value: 16, unit: '%' },
    ],
    passiveBuffs: [
      { label: 'Shame Purge', value: 14, unit: '%' },
      { label: 'Boundary Power', value: 16, unit: '%' },
    ],
    abilities: [
      { title: 'Infernal Focus', irl: 'Convert anger into a single task or boundary.' },
      { title: 'Sin Refinery', irl: 'Extract lesson, discard shame.' },
      { title: 'Crimson Mantle', irl: 'Command rooms via posture/tone.' },
      { title: 'Chains of Order', irl: 'Bind impulses to serve plans.' },
      { title: "Devil's Pact of Purpose", irl: 'Wounds become vows.' },
      { title: 'Demon Authority', irl: 'Dark charisma that compels action.' },
      { title: 'Hell Forge', irl: 'Pain creates unbreakable tools.' },
      { title: 'Shadow Integration', irl: 'Own your darkness completely.' },
      { title: 'Infernal Sovereignty', irl: 'Rule the underworld within.' },
      { title: 'Hogyoku Transcendence', irl: 'Limits dissolve into evolution.' },
    ],
    unlocked: true,
  },
  {
    id: 'thorn-ii',
    tier: 'Thorn',
    name: 'Thorn II — Dragon Emperor',
    order: 49,
    bpmRange: '205–225',
    energy: 'Chaos Emerald / Spirit Energy',
    jjkGrade: 'Special Elite',
    opTier: 'Yonko',
    activeBuffs: [
      { label: 'Emotional Literacy', value: 22, unit: '%' },
      { label: 'Command Voice', value: 18, unit: '%' },
    ],
    passiveBuffs: [
      { label: 'Justice-Mercy Balance', value: 18, unit: '%' },
      { label: 'Strategic Patience', value: 18, unit: '%' },
    ],
    abilities: [
      { title: 'Elemental Dominion', irl: 'Choose responses over reactions.' },
      { title: 'Wyrm Ascension', irl: 'Act instead of over-explain.' },
      { title: 'Scales of Equity', irl: 'Accountability without cruelty.' },
      { title: 'Roar of Command', irl: 'Unifying decisive communication.' },
      { title: 'Draconic Patience', irl: 'Know when not to respond.' },
      { title: 'Dragon Wisdom', irl: 'Ancient perspective on modern problems.' },
      { title: 'Chaos Emerald Power', irl: 'Harness disorder for transformation.' },
      { title: 'Wyrm Council', irl: 'Lead with terror and respect.' },
      { title: 'Elemental Mastery', irl: 'All energies bend to will.' },
      { title: 'Emperor Presence', irl: 'Reality shifts around your authority.' },
    ],
    unlocked: true,
  },
  {
    id: 'karma-iblis',
    tier: 'Karma',
    name: 'Iblis',
    order: 55,
    bpmRange: '95',
    energy: 'Cursed Energy',
    jjkGrade: 'Grade 2',
    opTier: 'Captain',
    activeBuffs: [
      { label: 'Anger Focus', value: 10, unit: '%' },
      { label: 'Endurance', value: 8, unit: '%' },
    ],
    passiveBuffs: [
      { label: 'Chaos Sterilization', value: 8, unit: '%' },
      { label: 'Infernal Calm', value: 10, unit: '%' },
    ],
    abilities: [
      { title: 'Wrath Lens', irl: 'Pick one constructive action when angry.' },
      { title: 'Heat Engine', irl: 'Stress fuels work instead of draining.' },
      { title: 'Ashen Mark', irl: 'Keep lessons, drop resentment.' },
      { title: 'Scorch Field', irl: 'Tone cuts through confusion.' },
      { title: 'Infernal Calm', irl: 'Stay logical while furious.' },
      { title: 'Rage Alchemy', irl: 'Transform fury into focused power.' },
      { title: 'Flame Guard', irl: 'Anger becomes protective boundary.' },
      { title: 'Iblis Fire', irl: 'Burn away what no longer serves.' },
      { title: 'Cursed Clarity', irl: 'See truth through emotional heat.' },
      { title: 'Hell Breath', irl: 'Exhale fury, inhale purpose.' },
    ],
    unlocked: true,
  },
  {
    id: 'karma-xeref',
    tier: 'Karma',
    name: 'Xeref',
    order: 56,
    bpmRange: '80',
    energy: 'Refined Cursed → Soul',
    jjkGrade: 'Grade 1',
    opTier: 'Vice Admiral',
    activeBuffs: [
      { label: 'Obsession Control', value: 10, unit: '%' },
      { label: 'Memory Systems', value: 10, unit: '%' },
    ],
    passiveBuffs: [
      { label: 'Habit Rewrite', value: 10, unit: '%' },
      { label: 'Patience', value: 10, unit: '%' },
    ],
    abilities: [
      { title: 'Obsession Focus', irl: 'Loop thoughts to insight without burnout.' },
      { title: 'Runic Memory', irl: 'Build durable note/tracking systems.' },
      { title: 'Curse Break', irl: 'Swap bad loops for rituals.' },
      { title: 'Echo Quill', irl: 'Writing that influences.' },
      { title: 'Time-Seal', irl: 'Detach from instant results.' },
      { title: 'Pattern Weaver', irl: 'See connections others miss.' },
      { title: 'Xeref Sight', irl: 'Obsession becomes strategic advantage.' },
      { title: 'Soul Archive', irl: 'Never forget important lessons.' },
      { title: 'Ritual Mind', irl: 'Structure defeats chaos.' },
      { title: 'Time Walker', irl: 'Patience outlasts urgency.' },
    ],
    unlocked: true,
  },
  {
    id: 'karma-ifrit',
    tier: 'Karma',
    name: 'Ifrit',
    order: 57,
    bpmRange: '75',
    energy: 'Flame / Rebirth',
    jjkGrade: 'Special (Low)',
    opTier: 'Rear Admiral',
    activeBuffs: [
      { label: 'Recovery Speed', value: 12, unit: '%' },
      { label: 'Motivation', value: 10, unit: '%' },
    ],
    passiveBuffs: [
      { label: 'Work-Rest Rhythm', value: 10, unit: '%' },
      { label: 'Enthusiasm Control', value: 8, unit: '%' },
    ],
    abilities: [
      { title: 'Phoenix Ignition', irl: 'Failure sparks rebirth.' },
      { title: 'Flame Cycle', irl: 'Work-recovery structure.' },
      { title: 'Molten Heart', irl: 'Passion burns clean.' },
      { title: 'Cinder Trail', irl: 'Small visible wins sustain momentum.' },
      { title: 'Fire Song', irl: 'Action replaces persuasion.' },
      { title: 'Resurrection Power', irl: 'Rise stronger from every fall.' },
      { title: 'Ifrit Core', irl: 'Eternal flame of motivation.' },
      { title: 'Ember Memory', irl: 'Past failures fuel future wins.' },
      { title: 'Rebirth Protocol', irl: 'Systematic renewal after setbacks.' },
      { title: 'Eternal Flame', irl: 'Enthusiasm never fully dies.' },
    ],
    unlocked: true,
  },
  {
    id: 'karma-igneel',
    tier: 'Karma',
    name: 'Igneel',
    order: 58,
    bpmRange: '70',
    energy: 'Dragon Ki',
    jjkGrade: 'Special',
    opTier: 'Admiral',
    activeBuffs: [
      { label: 'Protective Instinct', value: 14, unit: '%' },
      { label: 'Courage', value: 12, unit: '%' },
    ],
    passiveBuffs: [
      { label: 'Warmth', value: 12, unit: '%' },
      { label: 'Leadership First-Move', value: 12, unit: '%' },
    ],
    abilities: [
      { title: 'Dragon Heart', irl: 'Pride protects, not dominates.' },
      { title: 'Guardian Wing', irl: 'Shelter allies instinctively.' },
      { title: 'Solar Breath', irl: 'Encouragement energizes.' },
      { title: 'Courage Flare', irl: 'Lead first when others hesitate.' },
      { title: 'Legacy Oath', irl: 'Think in decades, not days.' },
      { title: 'Igneel Roar', irl: 'Voice that inspires generations.' },
      { title: 'Father Flame', irl: 'Nurture potential in others.' },
      { title: 'Dragon Pride', irl: 'Self-worth that uplifts community.' },
      { title: 'Protective Fire', irl: 'Defend what matters fiercely.' },
      { title: 'Legacy Builder', irl: 'Actions that outlive the actor.' },
    ],
    unlocked: true,
  },
  {
    id: 'regalia-hagoromo',
    tier: 'Regalia',
    name: 'Hagoromo Scarf',
    order: 68,
    bpmRange: '175–190',
    energy: 'Divine Charyeok / Aether',
    jjkGrade: 'Domain Candidate',
    opTier: 'Vice Admiral',
    activeBuffs: [
      { label: 'Compassion Aura', value: 16, unit: '%' },
      { label: 'Guidance', value: 14, unit: '%' },
    ],
    passiveBuffs: [
      { label: 'Clarity', value: 12, unit: '%' },
      { label: 'Haste Control', value: 12, unit: '%' },
    ],
    abilities: [
      { title: 'Mercy Field', irl: 'De-escalate conflict with tone and posture.' },
      { title: 'Wisdom Thread', irl: 'Apply lessons instantly.' },
      { title: 'Guiding Seal', irl: 'Short cues realign a group.' },
      { title: 'Aether Breath', irl: 'Breathe empathy in, clarity out.' },
      { title: "Healer's Oath", irl: 'Avoid harm through haste.' },
      { title: 'Hagoromo Grace', irl: 'Sage presence calms storms.' },
      { title: 'Divine Teaching', irl: 'Wisdom transfers through example.' },
      { title: 'Scarf Shield', irl: 'Compassion as defense.' },
      { title: 'Peace Weaver', irl: 'Create harmony from discord.' },
      { title: 'Sage Authority', irl: 'Gentle power that commands respect.' },
    ],
    unlocked: true,
  },
  {
    id: 'regalia-chakra-cloak',
    tier: 'Regalia',
    name: 'Chakra Cloak',
    order: 69,
    bpmRange: '195–210',
    energy: 'Spirit Armor / Aether',
    jjkGrade: 'Domain',
    opTier: 'Admiral',
    activeBuffs: [
      { label: 'Composure', value: 18, unit: '%' },
      { label: 'Integrity', value: 16, unit: '%' },
    ],
    passiveBuffs: [
      { label: 'Calm Facts', value: 16, unit: '%' },
      { label: 'Team Tempo', value: 14, unit: '%' },
    ],
    abilities: [
      { title: 'Serene Armor', irl: 'Emotional attacks dissolve.' },
      { title: 'Aura Circuit', irl: 'Balance body and mind.' },
      { title: 'Lotus Guard', irl: 'Purity in toxic settings.' },
      { title: 'Mirror Veil', irl: 'Reflect aggression without absorbing.' },
      { title: 'Still Pulse', irl: 'Your heartbeat sets team pace.' },
      { title: 'Chakra Flow', irl: 'Energy moves without blockage.' },
      { title: 'Spirit Fortress', irl: 'Unbreakable inner peace.' },
      { title: 'Cloak Defense', irl: 'Invisible protection always active.' },
      { title: 'Aura Mastery', irl: 'Control energy field completely.' },
      { title: 'Divine Shield', irl: 'Protected by higher power.' },
    ],
    unlocked: true,
  },
  {
    id: 'ouro-black-sun-crown',
    tier: 'Ouroboros',
    name: 'Black Sun Crown',
    order: 92,
    bpmRange: '290–310',
    energy: 'Law-Weaving Aether',
    jjkGrade: 'Transcendent',
    opTier: 'Imu-Class',
    activeBuffs: [
      { label: 'Law Creation', value: 30, unit: '%' },
      { label: 'Zero-Point Calm', value: 28, unit: '%' },
    ],
    passiveBuffs: [
      { label: 'Habit Alignment', value: 22, unit: '%' },
      { label: 'Cultural Standard', value: 22, unit: '%' },
    ],
    abilities: [
      { title: 'Law Writer', irl: "Intention drafts reality's script." },
      { title: 'Zero Point Calm', irl: 'Stillness produces energy.' },
      { title: 'Crown Circuit', irl: 'Thought-emotion-action perfect loop.' },
      { title: 'Solar Decree', irl: 'Acts model new standards.' },
      { title: 'Infinite Orbit', irl: 'Endings recycle into beginnings.' },
      { title: 'Black Sun Authority', irl: 'Commands that reshape reality.' },
      { title: 'Crown of Creation', irl: 'Build worlds from intention.' },
      { title: 'Aether Weaving', irl: 'Manipulate fundamental forces.' },
      { title: 'Law of Return', irl: 'What you create sustains you.' },
      { title: 'Sovereign Presence', irl: 'Existence itself bends around you.' },
    ],
    unlocked: true,
  },
  {
    id: 'bhc-stage1',
    tier: 'BlackHeart',
    name: 'Black Heart Core — Stage 1 (Awakening)',
    order: 109,
    bpmRange: '270',
    energy: 'Black Sun Energy',
    jjkGrade: 'Transcendent (Entry)',
    opTier: 'Imu-Class',
    activeBuffs: [
      { label: 'Calm Motivation', value: 26, unit: '%' },
      { label: 'Emotion Recycling', value: 24, unit: '%' },
    ],
    passiveBuffs: [
      { label: 'Purpose Clarity', value: 22, unit: '%' },
      { label: 'Ripple Impact', value: 20, unit: '%' },
    ],
    abilities: [
      { title: 'Heart Forge', irl: 'Calm generates motivation.' },
      { title: 'Soul Resonator', irl: 'Feel truth as vibration.' },
      { title: 'Shadowless Pulse', irl: 'All moods fuel focus.' },
      { title: 'Singularity Sight', irl: 'One path in noise.' },
      { title: 'Echo Creation', irl: 'Micro-habits shape outcomes.' },
      { title: 'Black Heart Beat', irl: 'Rhythm that aligns all systems.' },
      { title: 'Awakening Power', irl: 'Potential becomes kinetic.' },
      { title: 'Dark Sun Rising', irl: 'New paradigm emerges from within.' },
      { title: 'Core Synchronization', irl: 'Body-mind-soul unified.' },
      { title: 'Genesis Pulse', irl: 'Every moment is a new beginning.' },
    ],
    unlocked: true,
  },
  {
    id: 'bhc-stage3',
    tier: 'BlackHeart',
    name: 'Black Heart Core — Stage 3 (Omnipresence)',
    order: 111,
    bpmRange: '360+',
    energy: 'Singularity Aether (Unity)',
    jjkGrade: 'Cosmic',
    opTier: 'Beyond Celestial',
    activeBuffs: [
      { label: 'Omni-Awareness', value: 40, unit: '%' },
      { label: 'Infinite Energy Loop', value: 40, unit: '%' },
    ],
    passiveBuffs: [
      { label: 'Healing Presence', value: 30, unit: '%' },
      { label: 'Mission Alignment', value: 30, unit: '%' },
    ],
    abilities: [
      { title: 'Zero-Form Shift', irl: 'Attention equals presence.' },
      { title: 'Eternal Loop Drive', irl: 'Energy transforms, not depletes.' },
      { title: 'Law of Witness', irl: 'Observation stabilizes systems.' },
      { title: 'White-Within-Black Flame', irl: 'Peace and power co-manifest.' },
      { title: 'Aevara Return', irl: 'Mission, values, daily life align.' },
      { title: 'Omnipresent Awareness', irl: 'Conscious everywhere simultaneously.' },
      { title: 'Unity Field', irl: 'All beings connected through you.' },
      { title: 'Cosmic Healing', irl: 'Your presence heals systems.' },
      { title: 'Infinite Heart', irl: 'Love without limits or conditions.' },
      { title: 'Source Return', irl: 'Complete integration with origin.' },
    ],
    unlocked: true,
  },
  {
    id: 'hyperflame-spire',
    tier: 'FinalAscent',
    name: 'Hyperflame Spire',
    order: 145,
    bpmRange: '60–80',
    energy: 'System-Creation Flame',
    jjkGrade: 'Omni-Domain',
    opTier: 'Imu-Class',
    activeBuffs: [
      { label: 'Framework Instantiation', value: 28, unit: '%' },
      { label: 'Compounding Momentum', value: 24, unit: '%' },
    ],
    passiveBuffs: [
      { label: 'Blueprint + Detail Vision', value: 22, unit: '%' },
      { label: 'Teaching by Resonance', value: 22, unit: '%' },
    ],
    abilities: [
      { title: 'System Forge', irl: 'Conjure structures from intent.' },
      { title: 'Spiral Heat', irl: 'Momentum fuels innovation.' },
      { title: "Architect's Lens", irl: 'See blueprint and detail.' },
      { title: 'Pulse Replication', irl: 'Others learn via your rhythm.' },
      { title: 'Eternal Workshop', irl: 'Every act improves the system.' },
      { title: 'Framework Mastery', irl: 'Instant system design capability.' },
      { title: 'Compound Vision', irl: 'See how small actions compound.' },
      { title: 'Teaching Flame', irl: 'Knowledge spreads from your presence.' },
      { title: 'Spire Construction', irl: 'Build towers that reach infinity.' },
      { title: 'Innovation Loop', irl: 'Each creation births the next.' },
    ],
    unlocked: true,
  },
  {
    id: 'akudama-ascendant',
    tier: 'FinalAscent',
    name: 'Akudama Ascendant',
    order: 148,
    bpmRange: '50–90',
    energy: 'Axis Irregular Flame',
    jjkGrade: 'Omni-Domain+',
    opTier: 'Imu-Class+',
    activeBuffs: [
      { label: 'Rule-Rewrite', value: 30, unit: '%' },
      { label: 'Shadow Learning', value: 26, unit: '%' },
    ],
    passiveBuffs: [
      { label: 'Pattern Legacy', value: 24, unit: '%' },
      { label: 'Rebel Harmony', value: 24, unit: '%' },
    ],
    abilities: [
      { title: 'Axis Irregular', irl: 'Rewrite rules that define rules.' },
      { title: 'Shadow Scholar', irl: 'Learn from darkness cleanly.' },
      { title: 'Meta Signature', irl: 'Patterns that mentor by observation.' },
      { title: 'Rebel Harmony', irl: 'Challenge norms to modernize.' },
      { title: 'Singular Axis', irl: 'Align life around one purpose.' },
      { title: 'Law Breaker', irl: 'Transcend limitations others accept.' },
      { title: 'Akudama Code', irl: 'Ethics outside conventional morality.' },
      { title: 'Pattern Disruption', irl: 'Break cycles no one else can.' },
      { title: 'Irregular Flame', irl: 'Power from defying expectations.' },
      { title: 'Axis Sovereignty', irl: 'Define your own reality completely.' },
    ],
    unlocked: true,
  },
];
