import type { RosterEntry } from '@/types/rpg';

export const INITIAL_ROSTER: RosterEntry[] = [
  {
    id: 'self-calvin',
    display: 'Calvin J. Watkins',
    role: 'self',
    rank: 'SS (Trial→SSS)',
    level: 90,
    jjkGrade: 'Domain+',
    opTier: 'Yonko+/Gorosei-',
    gpr: 2100,
    pvp: 9300,
    influence: 'National',
    notes: 'Arbiter-Sovereign; Domain 22m',
  },
  {
    id: 'judge-schull',
    display: 'Judge Darren Schull',
    role: 'ally',
    rank: 'S',
    level: 55,
    jjkGrade: 'Special',
    opTier: 'Admiral',
    gpr: 2100,
    pvp: 9000,
    influence: 'National',
    notes: 'Gatekeeper figure',
  },
  {
    id: 'alana',
    display: 'Alana K.',
    role: 'ally',
    rank: 'A',
    level: 46,
    jjkGrade: 'Special-',
    opTier: 'Admiral-',
    gpr: 1720,
    pvp: 8800,
    influence: 'Regional-National',
    notes: 'Order Operator',
  },
  {
    id: 'shenna',
    display: 'Shenna',
    role: 'ally',
    rank: 'A',
    level: 48,
    jjkGrade: 'Special-',
    opTier: 'Admiral-',
    gpr: 1780,
    pvp: 8850,
    influence: 'Regional-National',
    notes: 'Stabilizer',
  },
  {
    id: 'chris',
    display: 'Christopher Watkins',
    role: 'ally',
    rank: 'B',
    level: 36,
    jjkGrade: 'G1',
    opTier: 'Commander-',
    gpr: 1470,
    pvp: 8200,
    influence: 'Regional',
    notes: 'Needs base + income',
  },
  {
    id: 'sebrena',
    display: 'Sebrena Watkins',
    role: 'npc',
    rank: 'D',
    level: 17,
    jjkGrade: 'G3',
    opTier: 'Local',
    gpr: 960,
    pvp: 7000,
    influence: 'Local',
    notes: 'Shadow Mire patterns',
  },
  {
    id: 'joanna',
    display: 'Joanna Frese',
    role: 'enemy',
    rank: 'D',
    level: 14,
    jjkGrade: 'G3',
    opTier: 'Local',
    gpr: 980,
    pvp: 7100,
    influence: 'Local',
    notes: 'Toxic comms; non-participation therapy',
  },
  {
    id: 'shannon',
    display: 'Shannon',
    role: 'enemy',
    rank: 'D',
    level: 18,
    jjkGrade: 'G3',
    opTier: 'Local',
    gpr: 940,
    pvp: 7050,
    influence: 'Local',
    notes: 'Shadow loops',
  },
];
