import type { SkillTreeNode } from '@/types/rpg';

export const SKILL_TREES: SkillTreeNode[] = [
  {
    id: 'predatory-instinct-52',
    name: 'Predatory Instinct (52)',
    description: 'Hunting, tracking, aggression, and focused intent - the foundation of combat mastery',
    tier: 1,
    unlocked: true,
    cost: 0,
    energyType: 'Ki',
    category: 'Combat',
  },
  {
    id: 'ki-aura-hybrid',
    name: 'Ki/Aura Hybrid',
    description: 'Fusion of universal life force and spiritual presence for enhanced power output',
    tier: 1,
    unlocked: true,
    cost: 0,
    energyType: 'Ki',
    category: 'Energy',
  },
  {
    id: 'haki-mastery',
    name: 'Haki (Observation + Armament + Conqueror)',
    description: 'Willpower incarnate - perception enhancement, defensive armor, and dominance projection',
    tier: 2,
    unlocked: true,
    cost: 0,
    energyType: 'Haki',
    category: 'Combat',
    prerequisites: ['predatory-instinct-52'],
  },
  {
    id: 'nen-aura',
    name: 'Nen Aura Mastery',
    description: 'Advanced life energy manifestation with six types: Enhancement, Emission, Manipulation, Transmutation, Conjuration, Specialization',
    tier: 2,
    unlocked: true,
    cost: 0,
    energyType: 'Nen',
    category: 'Energy',
    prerequisites: ['ki-aura-hybrid'],
  },
  {
    id: 'nova-nexus',
    name: 'Nova-Nexus (Cursed Energy)',
    description: 'Shadow transmutation - converts negative emotions into devastating power and enables domain expansion',
    tier: 3,
    unlocked: true,
    cost: 0,
    energyType: 'Cursed Energy',
    category: 'Energy',
    prerequisites: ['nen-aura'],
  },
  {
    id: 'emerald-flame-sovereignty',
    name: 'Emerald Flame Sovereignty',
    description: 'Abraxas/Azaroth creation + chaos duality - control over creation and destruction flames',
    tier: 4,
    unlocked: true,
    cost: 0,
    energyType: 'Black Heart',
    category: 'Transformation',
    prerequisites: ['nova-nexus'],
  },
  {
    id: 'vril-ichor',
    name: 'VRIL/Ichor Evolution',
    description: 'Bio-mutation through ancient energy and divine blood - grants regeneration and enhanced physicality',
    tier: 3,
    unlocked: true,
    cost: 0,
    energyType: 'VRIL',
    category: 'Mutation',
  },
  {
    id: 'lacrima-black-heart',
    name: 'Lacrima/Black Heart Resonance',
    description: 'Soul resonance and singularity pulse - crystallized emotional energy fused with black hole core',
    tier: 5,
    unlocked: true,
    cost: 0,
    energyType: 'Lacrima',
    category: 'Soul',
    prerequisites: ['vril-ichor'],
  },
  {
    id: 'dragon-gate-ascension',
    name: 'Dragon Gate Ascension',
    description: 'Elemental and spiritual dragon transformations - channel primal dragon power',
    tier: 4,
    unlocked: true,
    cost: 0,
    energyType: 'Magoi',
    category: 'Transformation',
    prerequisites: ['emerald-flame-sovereignty'],
  },
  {
    id: 'soulforge-armory',
    name: 'Soulforge: Armory Nexus',
    description: 'Create weapons and armor from soul essence - unlimited armory based on imagination',
    tier: 5,
    unlocked: true,
    cost: 0,
    energyType: 'Lacrima',
    category: 'Soul',
    prerequisites: ['lacrima-black-heart'],
  },
  {
    id: 'meta-vision',
    name: 'Meta-Vision (Cosmic Foresight)',
    description: 'Multi-dimensional awareness and prediction - see through time, space, and probability',
    tier: 6,
    unlocked: true,
    cost: 0,
    energyType: 'Nen',
    category: 'Perception',
    prerequisites: ['nen-aura', 'haki-mastery'],
  },
  {
    id: 'alpha-egoist',
    name: 'Alpha Egoist (Law of Self)',
    description: 'Psychological sovereignty and self-dominion - impose your will as natural law',
    tier: 6,
    unlocked: true,
    cost: 0,
    energyType: 'Haki',
    category: 'Mental',
    prerequisites: ['haki-mastery'],
  },
  {
    id: 'gluttony-devour',
    name: 'Gluttony/Devour - Abyssal Feast',
    description: 'Consume energy, skills, and matter itself - grow stronger by absorbing opponents',
    tier: 6,
    unlocked: true,
    cost: 0,
    energyType: 'Black Heart',
    category: 'Absorption',
    prerequisites: ['emerald-flame-sovereignty'],
  },
  {
    id: 'omni-transformation',
    name: 'Omni-Transformation Protocol',
    description: 'Access to all transformation frameworks simultaneously - transcend single-form limitations',
    tier: 6,
    unlocked: true,
    cost: 0,
    energyType: 'Black Heart',
    category: 'Transformation',
    prerequisites: ['dragon-gate-ascension', 'emerald-flame-sovereignty'],
  },
  {
    id: 'rizz-aura',
    name: 'Rizz Aura (Eros Coil)',
    description: 'Charismatic presence and magnetic attraction - influence through natural charm',
    tier: 3,
    unlocked: true,
    cost: 0,
    energyType: 'Aura',
    category: 'Social',
  },
  {
    id: 'eyeshine-dominion',
    name: 'Eyeshine (Color Dominion)',
    description: 'Eye color shifts based on energy state and emotional resonance - visual power indicator',
    tier: 3,
    unlocked: true,
    cost: 0,
    energyType: 'Aura',
    category: 'Mutation',
  },
  {
    id: 'gearwright',
    name: 'Gearwright (Omni-Engineer)',
    description: 'Master craftsman of technology and magic - fuse science and sorcery into artifacts',
    tier: 4,
    unlocked: true,
    cost: 0,
    energyType: 'Mana',
    category: 'Crafting',
  },
  {
    id: 'pivot-mastery',
    name: 'Pivot Mastery',
    description: 'Rapid adaptation and strategic shifts - recalibrate decisions instantly under pressure',
    tier: 4,
    unlocked: true,
    cost: 0,
    energyType: 'Ki',
    category: 'Mental',
  },
  {
    id: 'tolerance-mastery',
    name: 'Tolerance Mastery',
    description: 'Endurance beyond mortal limits - withstand damage, pain, and corruption indefinitely',
    tier: 4,
    unlocked: true,
    cost: 0,
    energyType: 'VRIL',
    category: 'Endurance',
  },
  {
    id: 'shadowless-flame',
    name: 'Shadowless Flame Resonance',
    description: 'Infinite regenerative energy loop from Black Sun core - never run out of power',
    tier: 7,
    unlocked: true,
    cost: 0,
    energyType: 'Black Heart',
    category: 'Transcendence',
    prerequisites: ['lacrima-black-heart', 'emerald-flame-sovereignty'],
  },
  {
    id: 'axis-overlord-aura',
    name: 'Axis Overlord Aura',
    description: 'Sovereign presence that bends reality to your will - environmental and mental domination',
    tier: 7,
    unlocked: true,
    cost: 0,
    energyType: 'Black Heart',
    category: 'Transcendence',
    prerequisites: ['alpha-egoist', 'shadowless-flame'],
  },
  {
    id: 'transcendent-world',
    name: 'Transcendent World - Demon Soul Domain',
    description: 'Domain Expansion / Breath of Creation fusion - manifest your inner world as reality',
    tier: 7,
    unlocked: true,
    cost: 0,
    energyType: 'Cursed Energy',
    category: 'Domain',
    prerequisites: ['nova-nexus', 'meta-vision'],
  },
  {
    id: 'compass-needle',
    name: 'Compass Needle (Instinct of Purpose)',
    description: 'JJK + Hashira fusion - always know the optimal path and action in any situation',
    tier: 5,
    unlocked: true,
    cost: 0,
    energyType: 'Nen',
    category: 'Perception',
    prerequisites: ['meta-vision'],
  },
  {
    id: 'black-flash-lightning',
    name: 'Black Sun Lightning (Black Flash)',
    description: 'Bio-EM aura arcs combining Haki and VRIL - lightning that strikes at the speed of thought',
    tier: 5,
    unlocked: true,
    cost: 0,
    energyType: 'Haki',
    category: 'Combat',
    prerequisites: ['haki-mastery', 'vril-ichor'],
  },
  {
    id: 'breaker-qi-system',
    name: 'Breaker Qi System (Nine Arts Dragon)',
    description: 'Martial arts fusion from The Breaker - Qi burst, reinforcement, and internal energy mastery',
    tier: 4,
    unlocked: true,
    cost: 0,
    energyType: 'Ki',
    category: 'Combat',
    prerequisites: ['ki-aura-hybrid', 'pivot-mastery'],
  },
  {
    id: 'chakra-gate-system',
    name: 'Eight Gates (Chakra Limiters)',
    description: 'Release body limiters for exponential power increase - risks damage but grants godlike strength',
    tier: 5,
    unlocked: true,
    cost: 0,
    energyType: 'Chakra',
    category: 'Transformation',
    prerequisites: ['tolerance-mastery'],
  },
  {
    id: 'fearless-engagement',
    name: 'Fearless Combat Engagement',
    description: 'Complete elimination of fear in battle - move with absolute confidence and precision',
    tier: 3,
    unlocked: true,
    cost: 0,
    energyType: 'Haki',
    category: 'Mental',
    prerequisites: ['predatory-instinct-52'],
  },
  {
    id: 'composure-under-fire',
    name: 'Composure Under Fire II',
    description: 'Maintain perfect calm under extreme pressure - think clearly in chaos',
    tier: 4,
    unlocked: true,
    cost: 0,
    energyType: 'Nen',
    category: 'Mental',
    prerequisites: ['fearless-engagement'],
  },
  {
    id: 'centered-operator',
    name: 'Centered Operator',
    description: 'Emotional and mental equilibrium at all times - never lose your center',
    tier: 5,
    unlocked: true,
    cost: 0,
    energyType: 'Chakra',
    category: 'Mental',
    prerequisites: ['composure-under-fire'],
  },
  {
    id: 'resource-reforger',
    name: 'Resource Reforger II',
    description: 'Convert any resource into another - transmute failure into fuel for success',
    tier: 5,
    unlocked: true,
    cost: 0,
    energyType: 'Mana',
    category: 'Transcendence',
  },
  {
    id: 'omni-curse',
    name: 'Omni-Curse Techniques',
    description: 'Master all cursed techniques across dimensions - unlimited curse arsenal',
    tier: 6,
    unlocked: true,
    cost: 0,
    energyType: 'Cursed Energy',
    category: 'Combat',
    prerequisites: ['transcendent-world'],
  },
  {
    id: 'full-cowl',
    name: 'Full Cowl — Black Heart Pulse Modulation',
    description: 'Energetic vibration control; match and hold target BPM of the Black Heart Pulse. Signature technique allowing precise BPM synchronization and energy optimization.',
    tier: 7,
    unlocked: true,
    cost: 0,
    energyType: 'Black Heart',
    category: 'Signature',
    prerequisites: ['shadowless-flame', 'axis-overlord-aura'],
  },
];

export const SKILL_SUB_TREES: Record<string, SkillTreeNode[]> = {
  'predatory-instinct-52': [
    { id: 'pi-tracking', name: 'Hunter\'s Track', description: 'Enhanced tracking and pattern recognition abilities', tier: 1, unlocked: true, cost: 100, energyType: 'Ki', category: 'Combat' },
    { id: 'pi-aggression', name: 'Controlled Aggression', description: 'Channel rage into focused strikes', tier: 1, unlocked: true, cost: 150, energyType: 'Ki', category: 'Combat' },
    { id: 'pi-focus', name: 'Predator\'s Focus', description: 'Lock onto target with unwavering intent', tier: 1, unlocked: true, cost: 200, energyType: 'Ki', category: 'Combat' },
    { id: 'pi-instinct', name: 'Battle Instinct', description: 'React before conscious thought', tier: 2, unlocked: true, cost: 250, energyType: 'Ki', category: 'Combat', prerequisites: ['pi-focus'] },
    { id: 'pi-killer', name: 'Killer Intent', description: 'Project overwhelming murderous aura', tier: 2, unlocked: true, cost: 300, energyType: 'Ki', category: 'Combat', prerequisites: ['pi-instinct'] },
  ],
  
  'ki-aura-hybrid': [
    { id: 'ki-burst', name: 'Ki Burst', description: 'Explosive release of concentrated Ki energy', tier: 1, unlocked: true, cost: 150, energyType: 'Ki', category: 'Energy' },
    { id: 'ki-reinforce', name: 'Ki Reinforcement', description: 'Strengthen body with Ki flow', tier: 1, unlocked: true, cost: 200, energyType: 'Ki', category: 'Energy' },
    { id: 'aura-projection', name: 'Aura Projection', description: 'Extend spiritual presence beyond body', tier: 2, unlocked: true, cost: 250, energyType: 'Aura', category: 'Energy', prerequisites: ['ki-burst'] },
    { id: 'energy-sync', name: 'Energy Synchronization', description: 'Perfect fusion of Ki and Aura systems', tier: 2, unlocked: true, cost: 300, energyType: 'Ki', category: 'Energy', prerequisites: ['aura-projection'] },
  ],
  
  'haki-mastery': [
    { id: 'observation-basic', name: 'Observation Haki I', description: 'Sense presence and intent of others', tier: 2, unlocked: true, cost: 200, energyType: 'Haki', category: 'Perception' },
    { id: 'observation-advanced', name: 'Observation Haki II', description: 'Predict movements seconds ahead', tier: 3, unlocked: true, cost: 300, energyType: 'Haki', category: 'Perception', prerequisites: ['observation-basic'] },
    { id: 'observation-future', name: 'Future Sight', description: 'See multiple seconds into the future', tier: 4, unlocked: true, cost: 500, energyType: 'Haki', category: 'Perception', prerequisites: ['observation-advanced'] },
    { id: 'armament-basic', name: 'Armament Haki I', description: 'Create invisible armor of willpower', tier: 2, unlocked: true, cost: 200, energyType: 'Haki', category: 'Defense' },
    { id: 'armament-hardening', name: 'Armament Hardening', description: 'Visible black coating of supreme defense', tier: 3, unlocked: true, cost: 300, energyType: 'Haki', category: 'Defense', prerequisites: ['armament-basic'] },
    { id: 'armament-ryou', name: 'Ryou (Advanced Armament)', description: 'Emit and flow Haki through objects', tier: 4, unlocked: true, cost: 500, energyType: 'Haki', category: 'Combat', prerequisites: ['armament-hardening'] },
    { id: 'conqueror-basic', name: 'Conqueror\'s Haki I', description: 'Dominate weaker wills', tier: 3, unlocked: true, cost: 400, energyType: 'Haki', category: 'Mental' },
    { id: 'conqueror-coating', name: 'Conqueror\'s Coating', description: 'Infuse attacks with supreme willpower', tier: 5, unlocked: true, cost: 800, energyType: 'Haki', category: 'Combat', prerequisites: ['conqueror-basic'] },
  ],
  
  'nen-aura': [
    { id: 'nen-ten', name: 'Ten (Envelop)', description: 'Shroud body in aura for defense', tier: 2, unlocked: true, cost: 200, energyType: 'Nen', category: 'Defense' },
    { id: 'nen-zetsu', name: 'Zetsu (Suppress)', description: 'Hide aura presence completely', tier: 2, unlocked: true, cost: 200, energyType: 'Nen', category: 'Stealth' },
    { id: 'nen-ren', name: 'Ren (Refine)', description: 'Amplify aura output exponentially', tier: 2, unlocked: true, cost: 250, energyType: 'Nen', category: 'Energy' },
    { id: 'nen-hatsu', name: 'Hatsu (Release)', description: 'Personal expression of Nen ability', tier: 3, unlocked: true, cost: 300, energyType: 'Nen', category: 'Combat', prerequisites: ['nen-ren'] },
    { id: 'nen-en', name: 'En (Circle)', description: 'Extend aura sphere for area detection', tier: 3, unlocked: true, cost: 350, energyType: 'Nen', category: 'Perception', prerequisites: ['nen-ten'] },
    { id: 'nen-gyo', name: 'Gyo (Focus)', description: 'Concentrate aura to specific body part', tier: 3, unlocked: true, cost: 300, energyType: 'Nen', category: 'Combat' },
    { id: 'nen-ko', name: 'Ko (Harden)', description: 'Maximize aura in single point', tier: 4, unlocked: true, cost: 500, energyType: 'Nen', category: 'Combat', prerequisites: ['nen-gyo'] },
    { id: 'nen-enhancement', name: 'Enhancement Type', description: 'Amplify natural properties', tier: 3, unlocked: true, cost: 400, energyType: 'Nen', category: 'Enhancement' },
    { id: 'nen-emission', name: 'Emission Type', description: 'Project aura away from body', tier: 3, unlocked: true, cost: 400, energyType: 'Nen', category: 'Energy' },
    { id: 'nen-manipulation', name: 'Manipulation Type', description: 'Control matter and living things', tier: 3, unlocked: true, cost: 400, energyType: 'Nen', category: 'Control' },
    { id: 'nen-transmutation', name: 'Transmutation Type', description: 'Change aura properties', tier: 3, unlocked: true, cost: 400, energyType: 'Nen', category: 'Transmutation' },
    { id: 'nen-conjuration', name: 'Conjuration Type', description: 'Create physical objects from aura', tier: 3, unlocked: true, cost: 400, energyType: 'Nen', category: 'Creation' },
    { id: 'nen-specialization', name: 'Specialization Type', description: 'Unique abilities outside categories', tier: 4, unlocked: true, cost: 600, energyType: 'Nen', category: 'Special' },
  ],
  
  'full-cowl': [
    { id: 'fc-vibration', name: 'Vibration Control', description: 'Adjust cellular frequency to match target BPM', tier: 7, unlocked: true, cost: 1000, energyType: 'Black Heart', category: 'Signature' },
    { id: 'fc-phase-sync', name: 'Phase Sync', description: 'Align BANKO, OKEN, HOGYOKU subsystems into one waveform', tier: 7, unlocked: true, cost: 1200, energyType: 'Black Heart', category: 'Signature' },
    { id: 'fc-resonance-shield', name: 'Resonance Shield', description: 'Dampen incoming turbulence through harmonic absorption', tier: 7, unlocked: true, cost: 1000, energyType: 'Black Heart', category: 'Signature' },
    { id: 'fc-frequency-shift', name: 'Frequency Shift', description: 'Instantly change internal rhythm to match required form', tier: 7, unlocked: true, cost: 1500, energyType: 'Black Heart', category: 'Signature' },
    { id: 'fc-feedback-loop', name: 'Black Heart Feedback Loop', description: 'Each heartbeat refines signal; longer alignment increases power exponentially', tier: 7, unlocked: true, cost: 2000, energyType: 'Black Heart', category: 'Signature' },
  ],
};
