import type { CouncilMember } from '@/types/rpg';

export const ALL_COUNCIL_MEMBERS: CouncilMember[] = [
  {
    id: 'arthur',
    name: 'Arthur',
    role: 'Arbiter',
    specialty: 'Noble authority and strategic command',
    class: 'core',
    notes: 'Decision seal; final judgment on critical choices',
  },
  {
    id: 'kaiyzer',
    name: 'Kaiyzer',
    role: 'Architect',
    specialty: 'Revolutionary thinking and change',
    class: 'core',
    notes: 'System designs; structure and framework builder',
  },
  {
    id: 'toji',
    name: 'Toji / Kai118',
    role: 'Executioner',
    specialty: 'Mastery through limitation',
    class: 'core',
    notes: 'Decisive action; gets things done without hesitation',
  },
  {
    id: 'yato',
    name: 'Yato / Raizo118',
    role: 'Phantom Judge',
    specialty: 'Survival and transformation',
    class: 'core',
    notes: 'Stealth strategy; operates in shadows',
  },
  {
    id: 'kratos',
    name: 'Kratos',
    role: 'Enforcer',
    specialty: 'Overcoming insurmountable odds',
    class: 'core',
    notes: 'Boundary power; maintains discipline',
  },
  {
    id: 'skar',
    name: 'Skar',
    role: 'Silent Hunter',
    specialty: 'Endurance through hardship',
    class: 'core',
    notes: 'Discipline and focus; patient observer',
  },
  {
    id: 'caliburn',
    name: 'Caliburn',
    role: 'Sacred Blade',
    specialty: 'Perfect execution and focus',
    class: 'core',
    notes: 'Soul resonance; spiritual alignment',
  },
  {
    id: 'homelander',
    name: 'Homelander',
    role: 'Power Archetype',
    specialty: 'Absolute power and presence',
    class: 'advisory',
    notes: 'Dominance and presence; unfiltered strength',
  },
  {
    id: 'billy-butcher',
    name: 'Billy Butcher',
    role: 'Ruthless Strategist',
    specialty: 'Strategic ruthlessness',
    class: 'advisory',
    notes: 'Do what needs doing; pragmatic action',
  },
  {
    id: 'ghost',
    name: 'James "Ghost" St Patrick',
    role: 'Strategic Operator',
    specialty: 'Invisible operations',
    class: 'advisory',
    notes: 'Business and street intelligence',
  },
  {
    id: 'jinwoo',
    name: 'Sung Jinwoo',
    role: 'Solo Leveling',
    specialty: 'Exponential growth',
    class: 'advisory',
    notes: 'Self-sufficiency and growth mindset',
  },
  {
    id: 'baam',
    name: 'Baam',
    role: 'Tower Climber',
    specialty: 'Tower climbing mentality',
    class: 'advisory',
    notes: 'Relentless ascension; loyalty and bonds',
  },
  {
    id: 'eren',
    name: 'Eren Yeager',
    role: 'Freedom Fighter',
    specialty: 'Breaking chains at any cost',
    class: 'advisory',
    notes: 'Breaking chains; radical change',
  },
  {
    id: 'all-might',
    name: 'All Might',
    role: 'Symbol of Peace',
    specialty: 'Hope and justice',
    class: 'advisory',
    notes: 'Inspire through presence; protect',
  },
  {
    id: 'madara',
    name: 'Madara Uchiha',
    role: 'World Shaper',
    specialty: 'Long-term planning',
    class: 'advisory',
    notes: 'Grand vision; reshape reality',
  },
  {
    id: 'tyler',
    name: 'Tyler Durden',
    role: 'Chaos Agent',
    specialty: 'Chaos as catalyst',
    class: 'advisory',
    notes: 'Break illusions; authentic self',
  },
  {
    id: 'evan',
    name: 'Evan',
    role: 'Mind Architect',
    specialty: 'Integration of opposing forces',
    class: 'advisory',
    notes: 'Psychological frameworks',
  },
  {
    id: 'magneto',
    name: 'Magneto',
    role: 'Revolution Leader',
    specialty: 'Righteous cause through force',
    class: 'advisory',
    notes: 'Stand for your people; magnetic leadership',
  },
  {
    id: 'jobs',
    name: 'Steve Jobs',
    role: 'Innovation Visionary',
    specialty: 'Simplicity and elegance',
    class: 'think-tank',
    notes: 'Design-first thinking; ruthless simplicity',
  },
  {
    id: 'tesla',
    name: 'Nikola Tesla',
    role: 'Inventor',
    specialty: 'Visionary technology',
    class: 'think-tank',
    notes: 'Pure genius; electromagnetic mastery',
  },
  {
    id: 'franklin',
    name: 'Benjamin Franklin',
    role: 'Polymath',
    specialty: 'Practical philosophy',
    class: 'think-tank',
    notes: 'Practical wisdom; systems thinking',
  },
  {
    id: 'bruce-lee',
    name: 'Bruce Lee',
    role: 'Martial Philosopher',
    specialty: 'Adaptive martial arts',
    class: 'think-tank',
    notes: 'Be like water; adapt and flow',
  },
  {
    id: 'musk',
    name: 'Elon Musk',
    role: 'Engineering Titan',
    specialty: 'Impossible made possible',
    class: 'think-tank',
    notes: 'First principles; impossible made real',
  },
  {
    id: 'ali',
    name: 'Muhammad Ali',
    role: 'Champion',
    specialty: 'Self-belief and showmanship',
    class: 'think-tank',
    notes: 'Confidence and conviction; float like butterfly',
  },
  {
    id: 'kiyosaki',
    name: 'Robert Kiyosaki',
    role: 'Financial Educator',
    specialty: 'Financial intelligence',
    class: 'think-tank',
    notes: 'Money systems; cash flow mastery',
  },
  {
    id: 'davinci',
    name: 'Leonardo da Vinci',
    role: 'Renaissance Master',
    specialty: 'Multi-disciplinary mastery',
    class: 'think-tank',
    notes: 'Art meets science; curiosity driven',
  },
];
