import type { DailyRitual } from '@/types/rpg';

export const DAILY_RITUALS: DailyRitual[] = [
  {
    id: 'legal-action',
    name: 'Legal Action',
    description: 'Email counsel re: motion to modify time-sharing',
    type: 'legal',
    xpReward: 150,
    completed: false,
    streak: 0,
  },
  {
    id: 'business-action',
    name: 'Business Action',
    description: 'FAYD HOA outreach – shortlist 3 HOAs',
    type: 'business',
    xpReward: 150,
    completed: false,
    streak: 0,
  },
  {
    id: 'self-care-action',
    name: 'Self-Care Action',
    description: 'Mobility 20m + Hydrate 2L',
    type: 'self_care',
    xpReward: 50,
    completed: false,
    streak: 0,
  },
  {
    id: 'ymca-bootcamp',
    name: 'YMCA Bootcamp Session',
    description: 'Teach or attend YMCA bootcamp class',
    type: 'fitness',
    xpReward: 60,
    completed: false,
    streak: 0,
  },
  {
    id: 'aevara-breath',
    name: 'Aevara Breath Protocol (6-3-9)',
    description: 'Inhale 6 sec, hold 3, exhale 9 sec - 3 cycles',
    type: 'self_care',
    xpReward: 50,
    completed: false,
    streak: 0,
  },
  {
    id: 'bpm-tracking',
    name: 'BPM Session Tracking',
    description: 'Record at least one BPM session with notes',
    type: 'self_care',
    xpReward: 25,
    completed: false,
    streak: 0,
  },
  {
    id: 'council-consultation',
    name: 'Council Consultation',
    description: 'Reflect on guidance from one of your councils',
    type: 'other',
    xpReward: 75,
    completed: false,
    streak: 0,
  },
  {
    id: 'codex-journaling',
    name: 'MemoryCodex Entry',
    description: 'Write a journal entry about your progress',
    type: 'other',
    xpReward: 50,
    completed: false,
    streak: 0,
  },
];
