import type { TransformationData, EnergySystem } from '@/types/rpg';

export const SPARTAN_TRANSFORMATIONS: TransformationData[] = [
  {
    id: 'spartan-cadet',
    tier: 'Spartan',
    name: 'Cadet',
    order: 1,
    bpmRange: '62-70',
    category: 'Spartan',
    description: 'Foundation of discipline and resolve',
    energy: 'VRIL, Ki',
    jjkGrade: 'Grade 3',
    opTier: 'Base',
    activeBuffs: [],
    passiveBuffs: [],
    abilities: [],
    unlocked: true,
  },
  {
    id: 'spartan-ranger',
    tier: 'Spartan',
    name: 'Ranger',
    order: 2,
    bpmRange: '72-80',
    category: 'Spartan',
    description: 'Observation and adaptability',
    energy: 'VRIL, Ki',
    jjkGrade: 'Grade 2',
    opTier: 'Base',
    activeBuffs: [],
    passiveBuffs: [],
    abilities: [],
    unlocked: true,
  },
  {
    id: 'spartan-ikari',
    tier: 'Spartan',
    name: 'Ikari/Claymore',
    order: 3,
    bpmRange: '88-104',
    category: 'Spartan',
    description: 'Transform pain into power',
    energy: 'VRIL, Ki, Cursed Energy',
    jjkGrade: 'Grade 1',
    opTier: 'Advanced',
    activeBuffs: [],
    passiveBuffs: [],
    abilities: [],
    unlocked: true,
  },
  {
    id: 'spartan-hashira',
    tier: 'Spartan',
    name: 'Hashira',
    order: 4,
    bpmRange: '96-110',
    category: 'Spartan',
    description: 'Precision and breath control',
    energy: 'VRIL, Ki, Chakra',
    jjkGrade: 'Grade 1',
    opTier: 'Advanced',
    activeBuffs: [],
    passiveBuffs: [],
    abilities: [],
    unlocked: true,
  },
  {
    id: 'spartan-kizuki',
    tier: 'Spartan',
    name: 'Kizuki',
    order: 5,
    bpmRange: '112-126',
    category: 'Spartan',
    description: 'Mutation and evolution',
    energy: 'VRIL, Ki, Cursed Energy',
    jjkGrade: 'Special Grade',
    opTier: 'Elite',
    activeBuffs: [],
    passiveBuffs: [],
    abilities: [],
    unlocked: true,
  },
  {
    id: 'spartan-yonko',
    tier: 'Spartan',
    name: 'Yonko',
    order: 6,
    bpmRange: '128-140',
    category: 'Spartan',
    description: 'Authority and protection',
    energy: 'VRIL, Ki, Haki',
    jjkGrade: 'Special Grade',
    opTier: 'Yonko',
    activeBuffs: [],
    passiveBuffs: [],
    abilities: [],
    unlocked: true,
  },
];

export const SAIYAN_TRANSFORMATIONS: TransformationData[] = [
  {
    id: 'saiyan-base',
    tier: 'Saiyan',
    name: 'Base Saiyan',
    order: 1,
    bpmRange: '70-70',
    category: 'Saiyan',
    description: 'Balanced vital state',
    energy: 'Ki',
    jjkGrade: 'Grade 2',
    opTier: 'Base',
    activeBuffs: [],
    passiveBuffs: [],
    abilities: [],
    unlocked: true,
  },
  {
    id: 'saiyan-ssj1',
    tier: 'Saiyan',
    name: 'Super Saiyan 1',
    order: 2,
    bpmRange: '90-90',
    category: 'Saiyan',
    description: 'Controlled rage',
    energy: 'Ki',
    jjkGrade: 'Grade 1',
    opTier: 'Advanced',
    activeBuffs: [],
    passiveBuffs: [],
    abilities: [],
    unlocked: true,
  },
  {
    id: 'saiyan-ssj2',
    tier: 'Saiyan',
    name: 'Super Saiyan 2',
    order: 3,
    bpmRange: '105-105',
    category: 'Saiyan',
    description: 'Wrath tempered',
    energy: 'Ki',
    jjkGrade: 'Special Grade',
    opTier: 'Elite',
    activeBuffs: [],
    passiveBuffs: [],
    abilities: [],
    unlocked: true,
  },
  {
    id: 'saiyan-ssjg',
    tier: 'Regalia',
    name: 'Super Saiyan God',
    order: 4,
    bpmRange: '145-145',
    category: 'Saiyan',
    description: 'Serene divinity',
    energy: 'Ki, Ichor',
    jjkGrade: 'Special Grade',
    opTier: 'God Tier',
    activeBuffs: [],
    passiveBuffs: [],
    abilities: [],
    unlocked: true,
  },
  {
    id: 'saiyan-ssjb',
    tier: 'Regalia',
    name: 'Super Saiyan Blue',
    order: 5,
    bpmRange: '155-155',
    category: 'Saiyan',
    description: 'Balanced god-ki',
    energy: 'Ki, Ichor',
    jjkGrade: 'Special Grade',
    opTier: 'God Tier',
    activeBuffs: [],
    passiveBuffs: [],
    abilities: [],
    unlocked: true,
  },
  {
    id: 'saiyan-ui',
    tier: 'FinalAscent',
    name: 'Ultra Instinct',
    order: 6,
    bpmRange: '188-188',
    category: 'Saiyan',
    description: 'Autonomous flow',
    energy: 'Ki, Ichor',
    jjkGrade: 'Beyond Special',
    opTier: 'Transcendent',
    activeBuffs: [],
    passiveBuffs: [],
    abilities: [],
    unlocked: true,
  },
];

export const THORN_TRANSFORMATIONS: TransformationData[] = [
  {
    id: 'thorn-1',
    tier: 'Thorn',
    name: 'Thorn I: Demon Emperor',
    order: 1,
    bpmRange: '180-200',
    category: 'Thorn',
    description: 'Hogyoku fusion with Cursed Energy',
    energy: 'Cursed Energy, Mana',
    jjkGrade: 'Special Grade',
    opTier: 'God Tier',
    activeBuffs: [],
    passiveBuffs: [],
    abilities: [],
    unlocked: true,
  },
  {
    id: 'thorn-2',
    tier: 'Thorn',
    name: 'Thorn II: Dragon Emperor',
    order: 2,
    bpmRange: '205-225',
    category: 'Thorn',
    description: 'Chaos Emerald with Spirit Energy',
    energy: 'Cursed Energy, Lacrima',
    jjkGrade: 'Beyond Special',
    opTier: 'God Tier',
    activeBuffs: [],
    passiveBuffs: [],
    abilities: [],
    unlocked: true,
  },
  {
    id: 'thorn-3',
    tier: 'Thorn',
    name: 'Thorn III: Eldritch Emperor',
    order: 3,
    bpmRange: '230-260',
    category: 'Thorn',
    description: 'Oken Core with Eldritch Soul',
    energy: 'Cursed Energy, Mana, Ichor',
    jjkGrade: 'Beyond Special',
    opTier: 'Transcendent',
    activeBuffs: [],
    passiveBuffs: [],
    abilities: [],
    unlocked: true,
  },
];

export const KARMA_TRANSFORMATIONS: TransformationData[] = [
  {
    id: 'karma-iblis',
    tier: 'Karma',
    name: 'Iblis',
    order: 1,
    bpmRange: '95-95',
    category: 'Karma',
    description: 'Wrath transformed to focus',
    energy: 'Cursed Energy',
    jjkGrade: 'Grade 1',
    opTier: 'Advanced',
    activeBuffs: [],
    passiveBuffs: [],
    abilities: [],
    unlocked: true,
  },
  {
    id: 'karma-xeref',
    tier: 'Karma',
    name: 'Xeref',
    order: 2,
    bpmRange: '80-80',
    category: 'Karma',
    description: 'Obsession becomes vision',
    energy: 'Mana, Magoi',
    jjkGrade: 'Grade 1',
    opTier: 'Advanced',
    activeBuffs: [],
    passiveBuffs: [],
    abilities: [],
    unlocked: true,
  },
  {
    id: 'karma-ifrit',
    tier: 'Karma',
    name: 'Ifrit',
    order: 3,
    bpmRange: '75-75',
    category: 'Karma',
    description: 'Passion to rebirth',
    energy: 'Mana',
    jjkGrade: 'Grade 2',
    opTier: 'Base',
    activeBuffs: [],
    passiveBuffs: [],
    abilities: [],
    unlocked: true,
  },
  {
    id: 'karma-igneel',
    tier: 'Karma',
    name: 'Igneel',
    order: 4,
    bpmRange: '70-70',
    category: 'Karma',
    description: 'Pride to love',
    energy: 'Lacrima',
    jjkGrade: 'Grade 2',
    opTier: 'Base',
    activeBuffs: [],
    passiveBuffs: [],
    abilities: [],
    unlocked: true,
  },
  {
    id: 'karma-azaroth',
    tier: 'Karma',
    name: 'Azaroth',
    order: 5,
    bpmRange: '55-55',
    category: 'Karma',
    description: 'Detachment to awareness',
    energy: 'Mana, Chakra',
    jjkGrade: 'Grade 3',
    opTier: 'Base',
    activeBuffs: [],
    passiveBuffs: [],
    abilities: [],
    unlocked: true,
  },
];

export const REGALIA_TRANSFORMATIONS: TransformationData[] = [
  {
    id: 'regalia-hagoromo',
    tier: 'Regalia',
    name: 'Hagoromo Scarf',
    order: 1,
    bpmRange: '175-190',
    category: 'Regalia',
    description: 'Divine empathy',
    energy: 'Chakra, Ichor',
    jjkGrade: 'Special Grade',
    opTier: 'God Tier',
    activeBuffs: [],
    passiveBuffs: [],
    abilities: [],
    unlocked: true,
  },
  {
    id: 'regalia-cloak',
    tier: 'Regalia',
    name: 'Chakra Cloak',
    order: 2,
    bpmRange: '195-210',
    category: 'Regalia',
    description: 'Aura armor',
    energy: 'Chakra, Aura',
    jjkGrade: 'Special Grade',
    opTier: 'God Tier',
    activeBuffs: [],
    passiveBuffs: [],
    abilities: [],
    unlocked: true,
  },
  {
    id: 'regalia-crown',
    tier: 'Regalia',
    name: 'Monarch Crown',
    order: 3,
    bpmRange: '215-230',
    category: 'Regalia',
    description: 'Command of reality',
    energy: 'Chakra, Magoi, Haki',
    jjkGrade: 'Beyond Special',
    opTier: 'God Tier',
    activeBuffs: [],
    passiveBuffs: [],
    abilities: [],
    unlocked: true,
  },
];

export const AXIS_IGNIS_TRANSFORMATIONS: TransformationData[] = [
  {
    id: 'axis-ignis',
    tier: 'FinalAscent',
    name: 'Axis Ignis',
    order: 1,
    bpmRange: '240-260',
    category: 'Axis Ignis',
    description: 'Play state of a god',
    energy: 'Black Heart, VRIL',
    jjkGrade: 'Beyond Special',
    opTier: 'Transcendent',
    activeBuffs: [],
    passiveBuffs: [],
    abilities: [],
    unlocked: true,
  },
];

export const OUROBOROS_TRANSFORMATIONS: TransformationData[] = [
  {
    id: 'ouroboros-cycle',
    tier: 'Ouroboros',
    name: 'Ouroboros Cycle',
    order: 1,
    bpmRange: '250-270',
    category: 'Ouroboros',
    description: 'Eternal loop sustainment',
    energy: 'Black Heart, Ichor, VRIL',
    jjkGrade: 'Beyond Special',
    opTier: 'Transcendent',
    activeBuffs: [],
    passiveBuffs: [],
    abilities: [],
    unlocked: true,
  },
  {
    id: 'ouroboros-cloak',
    tier: 'Ouroboros',
    name: 'Black Sun Cloak',
    order: 2,
    bpmRange: '265-285',
    category: 'Ouroboros',
    description: 'Entropy absorption',
    energy: 'Black Heart',
    jjkGrade: 'Beyond Special',
    opTier: 'Transcendent',
    activeBuffs: [],
    passiveBuffs: [],
    abilities: [],
    unlocked: true,
  },
  {
    id: 'ouroboros-crown',
    tier: 'Ouroboros',
    name: 'Black Sun Crown',
    order: 3,
    bpmRange: '290-310',
    category: 'Ouroboros',
    description: 'Harmonized law rewriting',
    energy: 'Black Heart, VRIL, Ichor',
    jjkGrade: 'Beyond Special',
    opTier: 'Transcendent',
    activeBuffs: [],
    passiveBuffs: [],
    abilities: [],
    unlocked: true,
  },
];

export const BLACK_HEART_TRANSFORMATIONS: TransformationData[] = [
  {
    id: 'blackheart-1',
    tier: 'BlackHeart',
    name: 'Black Heart: Stage 1',
    order: 1,
    bpmRange: '270-280',
    category: 'Black Heart',
    description: 'Joyful creation',
    energy: 'Black Heart',
    jjkGrade: 'Beyond Special',
    opTier: 'Transcendent',
    activeBuffs: [],
    passiveBuffs: [],
    abilities: [],
    unlocked: true,
  },
  {
    id: 'blackheart-2',
    tier: 'BlackHeart',
    name: 'Black Heart: Stage 2',
    order: 2,
    bpmRange: '320-340',
    category: 'Black Heart',
    description: 'Demiurge authorship',
    energy: 'Black Heart',
    jjkGrade: 'Beyond Special',
    opTier: 'Transcendent',
    activeBuffs: [],
    passiveBuffs: [],
    abilities: [],
    unlocked: true,
  },
  {
    id: 'blackheart-3',
    tier: 'BlackHeart',
    name: 'Black Heart: Stage 3',
    order: 3,
    bpmRange: '360-380',
    category: 'Black Heart',
    description: 'Omnipresence and unity',
    energy: 'Black Heart',
    jjkGrade: 'Beyond Special',
    opTier: 'Transcendent',
    activeBuffs: [],
    passiveBuffs: [],
    abilities: [],
    unlocked: true,
  },
];

export const AKUDAMA_TRANSFORMATIONS: TransformationData[] = [
  {
    id: 'akudama',
    tier: 'FinalAscent',
    name: 'Akudama Ascendant',
    order: 1,
    bpmRange: '400-400',
    category: 'Akudama',
    description: 'Chaos Incarnate',
    energy: 'Black Heart, Cursed Energy, VRIL',
    jjkGrade: 'Beyond Special',
    opTier: 'Transcendent',
    activeBuffs: [],
    passiveBuffs: [],
    abilities: [],
    unlocked: true,
  },
];

export const AEVARA_TRANSFORMATIONS: TransformationData[] = [
  {
    id: 'aevara',
    tier: 'FinalAscent',
    name: 'Aevara Return Cycle',
    order: 1,
    bpmRange: '55-400',
    category: 'Aevara',
    description: 'Source reunion - eternal law-bearer',
    energy: 'Black Heart, VRIL, Ichor',
    jjkGrade: 'Beyond Special',
    opTier: 'Transcendent',
    activeBuffs: [],
    passiveBuffs: [],
    abilities: [],
    unlocked: true,
  },
];

export const ALL_TRANSFORMATIONS: TransformationData[] = [
  ...SPARTAN_TRANSFORMATIONS,
  ...SAIYAN_TRANSFORMATIONS,
  ...KARMA_TRANSFORMATIONS,
  ...THORN_TRANSFORMATIONS,
  ...REGALIA_TRANSFORMATIONS,
  ...AXIS_IGNIS_TRANSFORMATIONS,
  ...OUROBOROS_TRANSFORMATIONS,
  ...BLACK_HEART_TRANSFORMATIONS,
  ...AKUDAMA_TRANSFORMATIONS,
  ...AEVARA_TRANSFORMATIONS,
];
